using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaRiego.Api.Contracts;
using SistemaRiego.Api.Data;
using SistemaRiego.Api.Models;
using SistemaRiego.Api.Services;

namespace SistemaRiego.Api.Controllers;

[ApiController,Route("api/territory"),Authorize(Policy=Policies.Operator)]
public sealed class TerritoryController(AppDbContext db, TerritoryIntegrityService? integrity = null):ControllerBase
{
    private readonly TerritoryIntegrityService integrity = integrity ?? new TerritoryIntegrityService(db);
    [HttpGet("hierarchy")]
    public async Task<IActionResult> Hierarchy(CancellationToken ct)=>Ok(await db.UniversityCenters.AsNoTracking().AsSplitQuery().Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(c=>new{c.Id,c.Code,c.Name,c.Location,Farms=c.Farms.Where(f=>f.IsActive).Select(f=>new{f.Id,f.Code,f.Name,f.Location,f.Latitude,f.Longitude,Blocks=f.Blocks.Where(b=>b.IsActive).Select(b=>new{b.Id,b.Code,b.Name,b.AreaHectares,SoilType=b.SoilType!=null?b.SoilType.Name:null,Sectors=b.Sectors.Where(s=>s.IsActive).Select(s=>new{s.Id,s.Code,s.Name,s.AreaHectares,s.SlopePercent,s.BoundaryGeoJson,Zones=s.Zones.Where(z=>z.IsActive).Select(z=>new{z.Id,z.Code,z.Name,z.AreaHectares,Status=z.OperationalStatus.Name,z.OperationalStatusId,z.PrimarySensorId,Sensor=z.PrimarySensor!=null?z.PrimarySensor.Name:null,z.ValveDeviceId,Valve=z.ValveDevice!=null?z.ValveDevice.Name:null,z.Latitude,z.Longitude,z.BoundaryGeoJson,Sensors=z.Sensors.Select(a=>new{a.SensorId,a.Sensor.Name,a.IsPrimary}),Valves=z.Valves.Select(a=>new{a.DeviceId,a.Device.Name})})})})})}).ToListAsync(ct));

    [HttpGet("centers")] public async Task<IActionResult> Centers(CancellationToken ct)=>Ok(await db.UniversityCenters.AsNoTracking().OrderBy(x=>x.Name).ToListAsync(ct));
    [HttpPost("centers"),Authorize(Policy=Policies.Technician)] public async Task<IActionResult> CreateCenter(CenterRequest r,CancellationToken ct){var code=Code(r.Code);if(await db.UniversityCenters.AnyAsync(x=>x.Code==code,ct))return Conflict(Message("El código del centro ya existe."));var x=new UniversityCenter{Code=code,Name=r.Name.Trim(),Location=Trim(r.Location),Contact=Trim(r.Contact),IsActive=r.IsActive};db.Add(x);Audit("CENTER_CREATED",x.Code);await db.SaveChangesAsync(ct);return Ok(x);}
    [HttpGet("farms")] public async Task<IActionResult> Farms(CancellationToken ct)=>Ok(await db.Farms.AsNoTracking().Include(x=>x.UniversityCenter).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name,x.Location,x.Latitude,x.Longitude,x.IsActive,x.UniversityCenterId,Center=x.UniversityCenter.Name}).ToListAsync(ct));
    [HttpPost("farms"),Authorize(Policy=Policies.Technician)] public async Task<IActionResult> CreateFarm(FarmRequest r,CancellationToken ct){if(!await db.UniversityCenters.AnyAsync(x=>x.Id==r.UniversityCenterId&&x.IsActive,ct))return BadRequest(Message("El centro seleccionado no existe."));var x=new Farm{UniversityCenterId=r.UniversityCenterId,Code=Code(r.Code),Name=r.Name.Trim(),Location=Trim(r.Location),Latitude=r.Latitude,Longitude=r.Longitude,IsActive=r.IsActive};db.Add(x);Audit("FARM_CREATED",x.Code);await db.SaveChangesAsync(ct);return Ok(x);}
    [HttpGet("blocks")] public async Task<IActionResult> Blocks(CancellationToken ct)=>Ok(await db.FarmBlocks.AsNoTracking().Include(x=>x.Farm).Include(x=>x.SoilType).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name,x.AreaHectares,x.Description,x.IsActive,x.FarmId,Farm=x.Farm.Name,x.SoilTypeId,SoilType=x.SoilType!=null?x.SoilType.Name:null}).ToListAsync(ct));
    [HttpPost("blocks"),Authorize(Policy=Policies.Technician)] public async Task<IActionResult> CreateBlock(BlockRequest r,CancellationToken ct){if(r.AreaHectares<=0)return BadRequest(Message("El área debe ser mayor que cero."));var x=new FarmBlock{FarmId=r.FarmId,SoilTypeId=r.SoilTypeId,Code=Code(r.Code),Name=r.Name.Trim(),AreaHectares=r.AreaHectares,Description=Trim(r.Description),IsActive=r.IsActive};db.Add(x);Audit("BLOCK_CREATED",x.Code);await db.SaveChangesAsync(ct);return Ok(x);}
    [HttpGet("sectors")] public async Task<IActionResult> Sectors(CancellationToken ct)=>Ok(await db.IrrigationSectors.AsNoTracking().Include(x=>x.FarmBlock).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name,x.AreaHectares,x.SlopePercent,x.IsActive,x.FarmBlockId,Block=x.FarmBlock.Name,x.BoundaryGeoJson}).ToListAsync(ct));
    [HttpPost("sectors"),Authorize(Policy=Policies.Technician)] public async Task<IActionResult> CreateSector(SectorRequest r,CancellationToken ct){if(r.AreaHectares<=0)return BadRequest(Message("El área debe ser mayor que cero."));try{await integrity.ValidateSectorAsync(r,null,ct);}catch(Exception e)when(e is TerritoryIntegrityException or SpatialValidationException){return BadRequest(Message(e.Message));}var code=Code(r.Code);if(await db.IrrigationSectors.AnyAsync(x=>x.Code==code,ct))return Conflict(Message("El código del sector ya existe."));var x=new IrrigationSector{FarmBlockId=r.FarmBlockId,Code=code,Name=r.Name.Trim(),AreaHectares=r.AreaHectares,SlopePercent=r.SlopePercent,BoundaryGeoJson=Trim(r.BoundaryGeoJson),IsActive=r.IsActive};db.Add(x);Audit("SECTOR_CREATED",x.Code);await db.SaveChangesAsync(ct);return Ok(x);}
    [HttpGet("zones")] public async Task<IActionResult> Zones(CancellationToken ct)=>Ok(await db.IrrigationZones.AsNoTracking().Include(x=>x.IrrigationSector).Include(x=>x.OperationalStatus).Include(x=>x.PrimarySensor).Include(x=>x.ValveDevice).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Code,x.Name,x.AreaHectares,x.IsActive,x.IrrigationSectorId,Sector=x.IrrigationSector.Name,x.OperationalStatusId,Status=x.OperationalStatus.Name,x.PrimarySensorId,Sensor=x.PrimarySensor!=null?x.PrimarySensor.Name:null,x.ValveDeviceId,Valve=x.ValveDevice!=null?x.ValveDevice.Name:null,x.Latitude,x.Longitude,x.BoundaryGeoJson,Sensors=x.Sensors.Select(a=>new{a.SensorId,a.Sensor.Name,a.IsPrimary}),Valves=x.Valves.Select(a=>new{a.DeviceId,a.Device.Name})}).ToListAsync(ct));
    [HttpPost("zones"),Authorize(Policy=Policies.Technician)] public async Task<IActionResult> CreateZone(ZoneRequest r,CancellationToken ct){if(r.AreaHectares<=0)return BadRequest(Message("El área debe ser mayor que cero."));try{await integrity.ValidateZoneAsync(r,null,ct);}catch(Exception e)when(e is TerritoryIntegrityException or SpatialValidationException){return BadRequest(Message(e.Message));}var code=Code(r.Code);if(await db.IrrigationZones.AnyAsync(x=>x.Code==code,ct))return Conflict(Message("El código de la zona ya existe."));var x=new IrrigationZone{IrrigationSectorId=r.IrrigationSectorId,Code=code,Name=r.Name.Trim(),AreaHectares=r.AreaHectares,OperationalStatusId=r.OperationalStatusId,PrimarySensorId=r.PrimarySensorId,ValveDeviceId=r.ValveDeviceId,Latitude=r.Latitude,Longitude=r.Longitude,BoundaryGeoJson=Trim(r.BoundaryGeoJson),IsActive=r.IsActive};db.Add(x);Audit("ZONE_CREATED",x.Code);await db.SaveChangesAsync(ct);await integrity.SyncAssignmentsAsync(x,r,ct);await db.SaveChangesAsync(ct);return Ok(x);}

    [HttpPatch("{kind}/{id:guid}/toggle"),Authorize(Policy=Policies.Technician)]
    public async Task<IActionResult> Toggle(string kind,Guid id,CancellationToken ct){object? item=kind.ToLowerInvariant() switch{"centers"=>await db.UniversityCenters.FindAsync([id],ct),"farms"=>await db.Farms.FindAsync([id],ct),"blocks"=>await db.FarmBlocks.FindAsync([id],ct),"sectors"=>await db.IrrigationSectors.FindAsync([id],ct),"zones"=>await db.IrrigationZones.FindAsync([id],ct),_=>null};if(item is null)return NotFound();var property=item.GetType().GetProperty("IsActive")!;property.SetValue(item,!(bool)property.GetValue(item)!);Audit("TERRITORY_STATUS_CHANGED",$"{kind}:{id}");await db.SaveChangesAsync(ct);return NoContent();}
    private void Audit(string type,string detail)=>db.AccessAudits.Add(new AccessAudit{EventType=type,Detail=detail});
    private static object Message(string value)=>new{message=value}; private static string Code(string value)=>value.Trim().ToUpperInvariant().Replace(' ','_'); private static string? Trim(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
}
