// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRiego.Api.Data;

#nullable disable

namespace SistemaRiego.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817231804_Sprint3TerritoryAutomationOperations")]
    partial class Sprint3TerritoryAutomationOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.AccessAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AccessAudits");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CropTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CropTypeId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.CropCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ActualHarvestDate")
                        .HasColumnType("date");

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpectedHarvestDate")
                        .HasColumnType("date");

                    b.Property<Guid>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SowingDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("IrrigationZoneId");

                    b.ToTable("CropCycles");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.CropType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CropTypes");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.CropWaterRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("AllowedFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("AllowedUntil")
                        .HasColumnType("time");

                    b.Property<int>("BaseDurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseVolumeLiters")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FrequencyHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaximumMoisturePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("MaximumTemperatureCelsius")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MinimumMoisturePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("MinimumTemperatureCelsius")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid?>("PhenologicalStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SoilTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TargetMoisturePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("PhenologicalStageId");

                    b.HasIndex("SoilTypeId");

                    b.ToTable("CropWaterRequirements");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.DeviceBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DeviceBrands");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.DeviceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceBrandId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("DeviceModels");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UniversityCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UniversityCenterId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.FarmBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SoilTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FarmId");

                    b.HasIndex("SoilTypeId");

                    b.ToTable("FarmBlocks");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.GlobalParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GlobalParameters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Category = "Telemetría",
                            DataType = "integer",
                            Description = "Frecuencia predeterminada de envío de lecturas",
                            IsEditable = true,
                            Key = "TELEMETRY_INTERVAL_SECONDS",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "60"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Category = "Riego",
                            DataType = "integer",
                            Description = "Duración predeterminada de un evento de riego",
                            IsEditable = true,
                            Key = "DEFAULT_IRRIGATION_MINUTES",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "15"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Category = "Seguridad",
                            DataType = "integer",
                            Description = "Intentos fallidos antes del bloqueo temporal",
                            IsEditable = true,
                            Key = "MAX_LOGIN_ATTEMPTS",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Category = "Dispositivos",
                            DataType = "integer",
                            Description = "Minutos sin lecturas para considerar un sensor desconectado",
                            IsEditable = true,
                            Key = "SENSOR_OFFLINE_MINUTES",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        });
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IrrigationRunId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IrrigationRunId");

                    b.HasIndex("IrrigationZoneId");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("IoTCommands");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<string>("InstallationLocation")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCommunicationUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceModelId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("NodeId");

                    b.HasIndex("OperationalStatusId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("IoTDevices");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommunicationProtocol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCommunicationUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("OperationalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OperationalStatusId");

                    b.ToTable("IoTNodes");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalibrationOffset")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<string>("Channel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastReadingUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("MeasurementUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinimumValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("OperationalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeviceId");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("OperationalStatusId");

                    b.HasIndex("SensorTypeId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("IoTSensors");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("AllowedFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("AllowedUntil")
                        .HasColumnType("time");

                    b.Property<Guid?>("CropWaterRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HysteresisPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastDecision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumDurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumMoisturePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SuspendedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TargetMoisturePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CropWaterRequirementId");

                    b.HasIndex("IrrigationZoneId", "Name")
                        .IsUnique();

                    b.ToTable("IrrigationRules");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FlowRateLitersMinute")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("IrrigationRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlannedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedByEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationRuleId");

                    b.HasIndex("IrrigationZoneId", "RequestedAtUtc");

                    b.ToTable("IrrigationRuns");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationSector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FarmBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SlopePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FarmBlockId");

                    b.ToTable("IrrigationSectors");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IrrigationSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperationalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrimarySensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ValveDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IrrigationSectorId");

                    b.HasIndex("OperationalStatusId");

                    b.HasIndex("PrimarySensorId");

                    b.HasIndex("ValveDeviceId");

                    b.ToTable("IrrigationZones");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationZoneSensor", b =>
                {
                    b.Property<Guid>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("IrrigationZoneId", "SensorId");

                    b.HasIndex("SensorId");

                    b.ToTable("IrrigationZoneSensors");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationZoneValve", b =>
                {
                    b.Property<Guid>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IrrigationZoneId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("IrrigationZoneValves");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.MasterCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Code")
                        .IsUnique();

                    b.ToTable("MasterCatalogItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "SOIL_MOISTURE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sensor para medir humedad volumétrica",
                            IsActive = true,
                            Kind = 1,
                            Name = "Humedad del suelo",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "AIR_TEMPERATURE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sensor de temperatura del entorno",
                            IsActive = true,
                            Kind = 1,
                            Name = "Temperatura ambiente",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "RASPBERRY_PI",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gateway y controlador central",
                            IsActive = true,
                            Kind = 2,
                            Name = "Raspberry Pi",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "SENSOR_NODE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nodo distribuido de adquisición",
                            IsActive = true,
                            Kind = 2,
                            Name = "Nodo de sensores",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "SOLENOID_VALVE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actuador para apertura y cierre del riego",
                            IsActive = true,
                            Kind = 2,
                            Name = "Válvula solenoide",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "PERCENT",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = 3,
                            Name = "Porcentaje",
                            Symbol = "%",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "CELSIUS",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = 3,
                            Name = "Grados Celsius",
                            Symbol = "°C",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "LITER",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = 3,
                            Name = "Litro",
                            Symbol = "L",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Code = "ACTIVE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = 4,
                            Name = "Activo",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Code = "OFFLINE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = 4,
                            Name = "Sin conexión",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Code = "MAINTENANCE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = 4,
                            Name = "En mantenimiento",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Code = "FAILURE",
                            CreatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = 4,
                            Name = "Con falla",
                            UpdatedAtUtc = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.OperationalEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IrrigationRunId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationRunId");

                    b.HasIndex("IrrigationZoneId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("OperationalEvents");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("PasswordCredentials");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.PasswordRecoveryToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordRecoveryTokens");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.PhenologicalStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropId", "Sequence")
                        .IsUnique();

                    b.ToTable("PhenologicalStages");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.SensorCalibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedOffset")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<DateTime>("CalibratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CalibratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MeasuredValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ReferenceValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "CalibratedAtUtc");

                    b.ToTable("SensorCalibrations");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BatteryPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("int");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationZoneId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("SensorId", "CapturedAtUtc");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.SoilType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FieldCapacityPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("InfiltrationMillimetersHour")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaturationPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SoilTypes");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.UniversityCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UniversityCenters");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.ValveRuntimeState", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAckAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastReconciledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DeviceId");

                    b.HasIndex("IrrigationZoneId");

                    b.ToTable("ValveRuntimeStates");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterConsumptionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DurationMinutes")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FlowRateLitersMinute")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("IrrigationRunId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IrrigationZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("VolumeLiters")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("IrrigationRunId")
                        .IsUnique();

                    b.HasIndex("IrrigationZoneId");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("WaterConsumptionRecords");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterPump", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastStoppedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaximumRunMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinimumRestMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WaterTankId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WaterTankId");

                    b.ToTable("WaterPumps");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterSupplyEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FinalLevelLiters")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("InitialLevelLiters")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SuppliedLiters")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<Guid>("WaterPumpId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("WaterPumpId");

                    b.ToTable("WaterSupplyEvents");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterTank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CapacityLiters")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("CurrentLevelLiters")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("LastLevelReadingUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumFillPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MinimumSafePercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WaterTanks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Crop", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.CropType", "CropType")
                        .WithMany()
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.CropCycle", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.PhenologicalStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("CurrentStage");

                    b.Navigation("IrrigationZone");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.CropWaterRequirement", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.PhenologicalStage", "PhenologicalStage")
                        .WithMany()
                        .HasForeignKey("PhenologicalStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.SoilType", "SoilType")
                        .WithMany()
                        .HasForeignKey("SoilTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Crop");

                    b.Navigation("PhenologicalStage");

                    b.Navigation("SoilType");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.DeviceModel", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.DeviceBrand", "DeviceBrand")
                        .WithMany("Models")
                        .HasForeignKey("DeviceBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceBrand");

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Farm", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.UniversityCenter", "UniversityCenter")
                        .WithMany("Farms")
                        .HasForeignKey("UniversityCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UniversityCenter");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.FarmBlock", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.Farm", "Farm")
                        .WithMany("Blocks")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.SoilType", "SoilType")
                        .WithMany()
                        .HasForeignKey("SoilTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Farm");

                    b.Navigation("SoilType");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTCommand", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IoTDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.IrrigationRun", null)
                        .WithMany()
                        .HasForeignKey("IrrigationRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", null)
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTDevice", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.DeviceModel", "DeviceModel")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.IoTNode", "Node")
                        .WithMany("Devices")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "OperationalStatus")
                        .WithMany()
                        .HasForeignKey("OperationalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceModel");

                    b.Navigation("DeviceType");

                    b.Navigation("Node");

                    b.Navigation("OperationalStatus");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTNode", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "OperationalStatus")
                        .WithMany()
                        .HasForeignKey("OperationalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OperationalStatus");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTSensor", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IoTDevice", "Device")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "OperationalStatus")
                        .WithMany()
                        .HasForeignKey("OperationalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "SensorType")
                        .WithMany()
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("MeasurementUnit");

                    b.Navigation("OperationalStatus");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationRule", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.CropWaterRequirement", "CropWaterRequirement")
                        .WithMany()
                        .HasForeignKey("CropWaterRequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropWaterRequirement");

                    b.Navigation("IrrigationZone");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationRun", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IrrigationRule", "IrrigationRule")
                        .WithMany()
                        .HasForeignKey("IrrigationRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IrrigationRule");

                    b.Navigation("IrrigationZone");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationSector", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.FarmBlock", "FarmBlock")
                        .WithMany("Sectors")
                        .HasForeignKey("FarmBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FarmBlock");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationZone", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IrrigationSector", "IrrigationSector")
                        .WithMany("Zones")
                        .HasForeignKey("IrrigationSectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.MasterCatalogItem", "OperationalStatus")
                        .WithMany()
                        .HasForeignKey("OperationalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.IoTSensor", "PrimarySensor")
                        .WithMany()
                        .HasForeignKey("PrimarySensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.IoTDevice", "ValveDevice")
                        .WithMany()
                        .HasForeignKey("ValveDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IrrigationSector");

                    b.Navigation("OperationalStatus");

                    b.Navigation("PrimarySensor");

                    b.Navigation("ValveDevice");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationZoneSensor", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany("Sensors")
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.IoTSensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IrrigationZone");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationZoneValve", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IoTDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany("Valves")
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("IrrigationZone");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.OperationalEvent", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IrrigationRun", "IrrigationRun")
                        .WithMany()
                        .HasForeignKey("IrrigationRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IrrigationRun");

                    b.Navigation("IrrigationZone");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.PasswordCredential", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("SistemaRiego.Api.Models.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.PasswordRecoveryToken", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.PhenologicalStage", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.Crop", "Crop")
                        .WithMany("Stages")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.RolePermission", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.SensorCalibration", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IoTSensor", "Sensor")
                        .WithMany("Calibrations")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.SensorReading", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaRiego.Api.Models.IoTSensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IrrigationZone");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Session", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.UserRole", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.ValveRuntimeState", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IoTDevice", "Device")
                        .WithOne()
                        .HasForeignKey("SistemaRiego.Api.Models.ValveRuntimeState", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", null)
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterConsumptionRecord", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.IrrigationRun", "IrrigationRun")
                        .WithOne()
                        .HasForeignKey("SistemaRiego.Api.Models.WaterConsumptionRecord", "IrrigationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaRiego.Api.Models.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IrrigationRun");

                    b.Navigation("IrrigationZone");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterPump", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.WaterTank", "WaterTank")
                        .WithMany("Pumps")
                        .HasForeignKey("WaterTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WaterTank");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterSupplyEvent", b =>
                {
                    b.HasOne("SistemaRiego.Api.Models.WaterPump", "WaterPump")
                        .WithMany()
                        .HasForeignKey("WaterPumpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WaterPump");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Crop", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.DeviceBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.DeviceModel", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Farm", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.FarmBlock", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTDevice", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTNode", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IoTSensor", b =>
                {
                    b.Navigation("Calibrations");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationSector", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.IrrigationZone", b =>
                {
                    b.Navigation("Sensors");

                    b.Navigation("Valves");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.UniversityCenter", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.User", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SistemaRiego.Api.Models.WaterTank", b =>
                {
                    b.Navigation("Pumps");
                });
#pragma warning restore 612, 618
        }
    }
}
