// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { FormEvent, useCallback, useEffect, useState } from 'react'
import './advanced-modules.css'

const root=import.meta.env.VITE_API_URL??`http://${window.location.hostname}:5080/api`
async function request(path,token,options={}){let response;try{response=await fetch(root+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}})}catch{throw new Error('La API no está disponible.')}const data=response.status===204?null:await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message??`Solicitud rechazada (${response.status}).`);return data}
const now=()=>new Date(Date.now()+3600000).toISOString().slice(0,16)
const empty={8:{irrigationZoneId:'',waterSourceId:'',waterTankId:'',waterPumpId:'',pipeDiameterMillimeters:50,pipeLengthMeters:100,designFlowLitersMinute:24,minimumPressureBar:1.2,maximumPressureBar:3},9:{name:'',irrigationZoneId:'',minimumMoisturePercent:28,targetMoisturePercent:42,hysteresisPercent:2,priority:1,maximumDurationMinutes:20,allowedFrom:'05:00',allowedUntil:'08:00',allowedDays:'1,2,3,4,5,6,7',isEnabled:true,requiresSufficientEnergy:true},10:{name:'',irrigationZoneId:'',nextRunAtUtc:now(),recurrence:'Único',intervalDays:1,durationMinutes:15,flowRateLitersMinute:12,isActive:true},11:{code:'',name:'',type:'Pozo',maximumFlowLitersMinute:40,isActive:true,notes:''},12:{kind:'array',name:'',ratedPowerWatts:500,panelCount:2,isActive:true,capacityWattHours:2000,nominalVoltage:24,minimumSafeChargePercent:20,currentChargePercent:80,status:'Disponible',solarPanelArrayId:'',solarBatteryId:'',ratedCurrentAmps:30},13:{name:'Línea base',irrigationZoneId:'',litersPerEvent:300,anomalyThresholdPercent:25,validFromUtc:new Date().toISOString().slice(0,10),isActive:true},14:{kind:'Preventivo',title:'',equipmentType:'',equipmentId:'',technicianName:'',technicianEmail:'',commitmentAtUtc:now(),status:'Pendiente',notes:''},15:{name:'',alertType:'Todos',minimumSeverity:'Advertencia',channels:'Correo',recipients:'',dailySummary:false,weeklySummary:false,isActive:true}}
const titles={8:['Configuración hidráulica','Fuente, tanque, bomba, tubería, caudal, presión y estado operativo.'],9:['Administración de reglas','Alta de reglas, simulación segura e historial de evaluaciones.'],10:['Programación de riegos','Ejecuciones futuras únicas o recurrentes.'],11:['Fuentes y llenado automático','Fuentes de abastecimiento y umbrales de tanque.'],12:['Activos de energía solar','Paneles, baterías, controladores e historial de autonomía.'],13:['Ahorro y anomalías','Líneas base, ahorro calculado y consumos fuera de rango.'],14:['Órdenes de trabajo','Mantenimiento preventivo/correctivo, técnico y compromiso.'],15:['Reglas de notificación','Canales, destinatarios, resúmenes e historial de integración.'],16:['Reportería y Power BI','PDF operativos, vistas, relaciones y medidas DAX.'],17:['Configuración e integraciones','Datos generales, n8n, Power BI y versionado de reglas.']}
function Field({label,children}){return <label><span>{label}</span>{children}</label>}
function Bool({value,onChange,label='Activo'}){return <label className="am-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function Table({headers,items,render}){return <div className="am-table"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.length?items.map(render):<tr><td colSpan={headers.length}>Sin registros.</td></tr>}</tbody></table></div>}

export default function AdvancedModulesPanel({module,session,notify}){
 const token=session.accessToken,[catalogs,setCatalogs]=useState({zones:[],tanks:[],pumps:[],sources:[],arrays:[],batteries:[]}),[items,setItems]=useState([]),[secondary,setSecondary]=useState([]),[tertiary,setTertiary]=useState([]),[form,setForm]=useState(()=>({...empty[module]})),[busy,setBusy]=useState(false),[editing,setEditing]=useState(null)
 const getPath={8:'/advanced/hydraulics',9:'/automation/rules',10:'/advanced/schedules',11:'/advanced/sources',12:'/advanced/energy/assets',13:'/advanced/efficiency/baselines',14:'/advanced/work-orders',15:'/advanced/notification-rules',16:'/advanced/powerbi/model',17:'/settings'}[module]
 const load=useCallback(async()=>{const [c,data]=await Promise.all([request('/advanced/catalogs',token),request(getPath,token)]);setCatalogs(c);if(module===12){setItems(data.arrays);setSecondary([...data.batteries,...data.controllers]);setTertiary(await request('/advanced/energy/autonomy',token))}else if(module===16||module===17)setItems(data);else setItems(data);if(module===9)setSecondary(await request('/advanced/rules/evaluations',token));if(module===11)setSecondary(await request('/advanced/auto-fill',token));if(module===13)setSecondary((await request('/advanced/efficiency/analysis',token)).rows);if(module===14)setSecondary(await request('/maintenance/equipment',token));if(module===15)setSecondary(await request('/advanced/integrations/history',token));if(module===17)setSecondary(await request('/automation/rules',token))},[getPath,module,token])
 useEffect(()=>{load().catch(e=>notify(e.message))},[load,notify])
 const change=(key,value)=>setForm(x=>({...x,[key]:value})); const reset=()=>{setForm({...empty[module]});setEditing(null)}
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{let path=getPath,payload={...form},method=editing?'PUT':'POST';if(module===8){path='/advanced/hydraulics';method='POST';payload={...payload,waterSourceId:payload.waterSourceId||null,waterTankId:payload.waterTankId||null,waterPumpId:payload.waterPumpId||null}}if(module===9){path=editing?`/automation/rules/${editing}`:'/automation/rules';payload={...payload,cropWaterRequirementId:null};}if(module===11&&form.waterTankId)path='/advanced/auto-fill';if(module===12)path=`/advanced/energy/${form.kind==='array'?'arrays':form.kind==='battery'?'batteries':'controllers'}${editing?'/'+editing:''}`;if(module===13)payload={...payload,irrigationZoneId:payload.irrigationZoneId||null,validFromUtc:new Date(payload.validFromUtc).toISOString()};if(module===14){path='/advanced/work-orders'+(editing?'/'+editing:'');payload={...payload,commitmentAtUtc:new Date(payload.commitmentAtUtc).toISOString()}};if(module===15)path='/advanced/notification-rules'+(editing?'/'+editing:'');const totp=module===9?window.prompt('Código de autenticación de 6 dígitos para guardar la regla:')?.trim():'';if(module===9&&!totp)throw new Error('Se requiere el código de autenticación para guardar la regla.');await request(path,token,{method,headers:totp?{'X-TOTP-Code':totp}:{},body:JSON.stringify(payload)});notify('Registro guardado correctamente.');reset();await load()}catch(error){notify(error.message)}finally{setBusy(false)}}
 const remove=async(path)=>{setBusy(true);try{await request(path,token,{method:'DELETE'});notify('Registro eliminado.');await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 const edit=x=>{setEditing(x.id);setForm({...empty[module],...x,nextRunAtUtc:x.nextRunAtUtc?.slice(0,16)??empty[module]?.nextRunAtUtc,commitmentAtUtc:x.commitmentAtUtc?.slice(0,16)??empty[module]?.commitmentAtUtc,validFromUtc:x.validFromUtc?.slice(0,10)??empty[module]?.validFromUtc});window.scrollTo({top:0,behavior:'smooth'})}
 const options=(list)=><>{list.map(x=><option key={x.id} value={x.id}>{x.name}{x.code?` · ${x.code}`:''}</option>)}</>
 const run=async(path,message)=>{try{await request(path,token,{method:'POST'});notify(message);await load()}catch(e){notify(e.message)}}
 const summary=async period=>{try{const x=await request('/advanced/notifications/summary?period='+period,token);notify('Resumen '+x.period+': '+x.total+' alertas, '+x.critical+' críticas, '+x.active+' activas.')}catch(e){notify(e.message)}}
 const equipmentHistory=async x=>{try{setTertiary(await request('/maintenance/equipment/'+encodeURIComponent(x.type)+'/'+encodeURIComponent(x.id)+'/history',token))}catch(e){notify(e.message)}}
 const download=async(name)=>{const response=await fetch(`${root}/reports/${name}.pdf`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('No fue posible generar el PDF.');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`${name}.pdf`;a.click();URL.revokeObjectURL(url)}
 const title=titles[module]
 return <div className="am-page"><header><p>MÓDULO {module} · GESTIÓN COMPLETA</p><h1>{title[0]}</h1><span>{title[1]}</span></header>
 {module<=15&&<form className="am-form" onSubmit={submit}><h2>{editing?'Editar registro':'Nuevo registro'}</h2>
  {module===8&&<><Field label="Zona"><select required value={form.irrigationZoneId} onChange={e=>change('irrigationZoneId',e.target.value)}><option value="">Seleccionar</option>{options(catalogs.zones)}</select></Field><Field label="Fuente"><select value={form.waterSourceId} onChange={e=>change('waterSourceId',e.target.value||null)}><option value="">Sin asignar</option>{options(catalogs.sources)}</select></Field><Field label="Tanque"><select value={form.waterTankId} onChange={e=>change('waterTankId',e.target.value||null)}><option value="">Sin asignar</option>{options(catalogs.tanks)}</select></Field><Field label="Bomba"><select value={form.waterPumpId} onChange={e=>change('waterPumpId',e.target.value||null)}><option value="">Sin asignar</option>{options(catalogs.pumps)}</select></Field>{[['pipeDiameterMillimeters','Diámetro mm'],['pipeLengthMeters','Longitud m'],['designFlowLitersMinute','Caudal L/min'],['minimumPressureBar','Presión mínima bar'],['maximumPressureBar','Presión máxima bar']].map(([k,l])=><Field key={k} label={l}><input type="number" step=".1" required value={form[k]} onChange={e=>change(k,+e.target.value)}/></Field>)}</>}
  {module===9&&<><Field label="Nombre"><input required value={form.name} onChange={e=>change('name',e.target.value)}/></Field><Field label="Zona"><select required value={form.irrigationZoneId} onChange={e=>change('irrigationZoneId',e.target.value)}><option value="">Seleccionar</option>{options(catalogs.zones)}</select></Field>{[['minimumMoisturePercent','Humedad mínima %'],['targetMoisturePercent','Humedad objetivo %'],['hysteresisPercent','Histéresis %'],['priority','Prioridad'],['maximumDurationMinutes','Duración máxima min']].map(([k,l])=><Field key={k} label={l}><input type="number" step=".1" value={form[k]} onChange={e=>change(k,+e.target.value)}/></Field>)}<Field label="Desde"><input type="time" value={form.allowedFrom} onChange={e=>change('allowedFrom',e.target.value)}/></Field><Field label="Hasta"><input type="time" value={form.allowedUntil} onChange={e=>change('allowedUntil',e.target.value)}/></Field><Bool value={form.isEnabled} onChange={v=>change('isEnabled',v)}/><Bool label="Exigir energía suficiente" value={form.requiresSufficientEnergy} onChange={v=>change('requiresSufficientEnergy',v)}/></>}
  {module===10&&<><Field label="Nombre"><input required value={form.name} onChange={e=>change('name',e.target.value)}/></Field><Field label="Zona"><select required value={form.irrigationZoneId} onChange={e=>change('irrigationZoneId',e.target.value)}><option value="">Seleccionar</option>{options(catalogs.zones)}</select></Field><Field label="Próxima ejecución"><input type="datetime-local" value={form.nextRunAtUtc} onChange={e=>change('nextRunAtUtc',e.target.value)}/></Field><Field label="Recurrencia"><select value={form.recurrence} onChange={e=>change('recurrence',e.target.value)}><option>Único</option><option>Recurrente</option></select></Field>{form.recurrence==='Recurrente'&&<Field label="Cada (días)"><input type="number" min="1" value={form.intervalDays} onChange={e=>change('intervalDays',+e.target.value)}/></Field>}<Field label="Duración min"><input type="number" value={form.durationMinutes} onChange={e=>change('durationMinutes',+e.target.value)}/></Field><Field label="Caudal L/min"><input type="number" step=".1" value={form.flowRateLitersMinute} onChange={e=>change('flowRateLitersMinute',+e.target.value)}/></Field><Bool value={form.isActive} onChange={v=>change('isActive',v)}/></>}
  {module===11&&<>{form.waterTankId?<><Field label="Tanque"><select value={form.waterTankId} onChange={e=>change('waterTankId',e.target.value)}>{options(catalogs.tanks)}</select></Field><Field label="Bomba"><select value={form.waterPumpId} onChange={e=>change('waterPumpId',e.target.value)}>{options(catalogs.pumps)}</select></Field><Field label="Fuente"><select value={form.waterSourceId} onChange={e=>change('waterSourceId',e.target.value)}>{options(catalogs.sources)}</select></Field><Field label="Arrancar al %"><input type="number" value={form.startAtPercent??25} onChange={e=>change('startAtPercent',+e.target.value)}/></Field><Field label="Detener al %"><input type="number" value={form.stopAtPercent??90} onChange={e=>change('stopAtPercent',+e.target.value)}/></Field><Bool value={form.isEnabled??true} onChange={v=>change('isEnabled',v)}/></>:<><Field label="Código"><input required value={form.code} onChange={e=>change('code',e.target.value)}/></Field><Field label="Nombre"><input required value={form.name} onChange={e=>change('name',e.target.value)}/></Field><Field label="Tipo"><select value={form.type} onChange={e=>change('type',e.target.value)}><option>Pozo</option><option>Red municipal</option><option>Captación pluvial</option><option>Río</option></select></Field><Field label="Caudal máximo L/min"><input type="number" value={form.maximumFlowLitersMinute} onChange={e=>change('maximumFlowLitersMinute',+e.target.value)}/></Field><Bool value={form.isActive} onChange={v=>change('isActive',v)}/><button type="button" className="am-alt" onClick={()=>setForm({...form,waterTankId:catalogs.tanks[0]?.id??'',waterPumpId:catalogs.pumps[0]?.id??'',waterSourceId:catalogs.sources[0]?.id??'',startAtPercent:25,stopAtPercent:90,isEnabled:true})}>Configurar llenado</button></>}</>}
  {module===12&&<><Field label="Tipo de activo"><select value={form.kind} onChange={e=>change('kind',e.target.value)}><option value="array">Panel/arreglo</option><option value="battery">Batería</option><option value="controller">Controlador</option></select></Field><Field label="Nombre"><input required value={form.name} onChange={e=>change('name',e.target.value)}/></Field>{form.kind==='array'&&<><Field label="Potencia nominal W"><input type="number" value={form.ratedPowerWatts} onChange={e=>change('ratedPowerWatts',+e.target.value)}/></Field><Field label="Paneles"><input type="number" value={form.panelCount} onChange={e=>change('panelCount',+e.target.value)}/></Field><Bool value={form.isActive} onChange={v=>change('isActive',v)}/></>}{form.kind==='battery'&&<><Field label="Capacidad Wh"><input type="number" value={form.capacityWattHours} onChange={e=>change('capacityWattHours',+e.target.value)}/></Field><Field label="Voltaje"><input type="number" value={form.nominalVoltage} onChange={e=>change('nominalVoltage',+e.target.value)}/></Field><Field label="Mínimo %"><input type="number" value={form.minimumSafeChargePercent} onChange={e=>change('minimumSafeChargePercent',+e.target.value)}/></Field><Field label="Carga actual %"><input type="number" value={form.currentChargePercent} onChange={e=>change('currentChargePercent',+e.target.value)}/></Field></>}{form.kind==='controller'&&<><Field label="Arreglo"><select required value={form.solarPanelArrayId} onChange={e=>change('solarPanelArrayId',e.target.value)}><option value="">Seleccionar</option>{options(catalogs.arrays)}</select></Field><Field label="Batería"><select required value={form.solarBatteryId} onChange={e=>change('solarBatteryId',e.target.value)}><option value="">Seleccionar</option>{options(catalogs.batteries)}</select></Field><Field label="Corriente nominal A"><input type="number" value={form.ratedCurrentAmps} onChange={e=>change('ratedCurrentAmps',+e.target.value)}/></Field></>}</>}
  {module===13&&<><Field label="Nombre"><input value={form.name} onChange={e=>change('name',e.target.value)}/></Field><Field label="Zona (vacío = general)"><select value={form.irrigationZoneId} onChange={e=>change('irrigationZoneId',e.target.value)}><option value="">Todas</option>{options(catalogs.zones)}</select></Field><Field label="Litros por evento"><input type="number" value={form.litersPerEvent} onChange={e=>change('litersPerEvent',+e.target.value)}/></Field><Field label="Umbral anomalía %"><input type="number" value={form.anomalyThresholdPercent} onChange={e=>change('anomalyThresholdPercent',+e.target.value)}/></Field><Field label="Vigente desde"><input type="date" value={form.validFromUtc} onChange={e=>change('validFromUtc',e.target.value)}/></Field><Bool value={form.isActive} onChange={v=>change('isActive',v)}/></>}
  {module===14&&<><Field label="Tipo"><select value={form.kind} onChange={e=>change('kind',e.target.value)}><option>Preventivo</option><option>Correctivo</option></select></Field><Field label="Trabajo"><input required value={form.title} onChange={e=>change('title',e.target.value)}/></Field><Field label="Equipo"><select required value={`${form.equipmentType}|${form.equipmentId}`} onChange={e=>{const [t,id]=e.target.value.split('|');setForm({...form,equipmentType:t,equipmentId:id})}}><option value="|">Seleccionar</option>{secondary.map(x=><option key={`${x.type}|${x.id}`} value={`${x.type}|${x.id}`}>{x.type} · {x.name}</option>)}</select></Field><Field label="Técnico"><input value={form.technicianName} onChange={e=>change('technicianName',e.target.value)}/></Field><Field label="Correo"><input type="email" value={form.technicianEmail} onChange={e=>change('technicianEmail',e.target.value)}/></Field><Field label="Fecha compromiso"><input type="datetime-local" value={form.commitmentAtUtc} onChange={e=>change('commitmentAtUtc',e.target.value)}/></Field><Field label="Estado"><select value={form.status} onChange={e=>change('status',e.target.value)}><option>Pendiente</option><option>En proceso</option><option>Completada</option><option>Cancelada</option></select></Field></>}
  {module===15&&<><Field label="Nombre"><input required value={form.name} onChange={e=>change('name',e.target.value)}/></Field><Field label="Tipo de alerta"><input value={form.alertType} onChange={e=>change('alertType',e.target.value)}/></Field><Field label="Severidad mínima"><select value={form.minimumSeverity} onChange={e=>change('minimumSeverity',e.target.value)}><option>Informativa</option><option>Advertencia</option><option>Crítica</option></select></Field><Field label="Canales"><input placeholder="Correo,Telegram,Teams,n8n" value={form.channels} onChange={e=>change('channels',e.target.value)}/></Field><Field label="Destinatarios"><input value={form.recipients} onChange={e=>change('recipients',e.target.value)}/></Field><Bool label="Resumen diario" value={form.dailySummary} onChange={v=>change('dailySummary',v)}/><Bool label="Resumen semanal" value={form.weeklySummary} onChange={v=>change('weeklySummary',v)}/><Bool value={form.isActive} onChange={v=>change('isActive',v)}/></>}
  <div className="am-actions"><button disabled={busy}>{editing?'Guardar cambios':'Guardar'}</button>{editing&&<button type="button" onClick={reset}>Cancelar</button>}</div></form>}
 {module===8&&<><Table headers={['Zona','Tubería','Caudal','Presión']} items={items} render={x=><tr key={x.id}><td>{x.irrigationZone?.name}</td><td>{x.pipeDiameterMillimeters} mm · {x.pipeLengthMeters} m</td><td>{x.designFlowLitersMinute} L/min</td><td>{x.minimumPressureBar}–{x.maximumPressureBar} bar</td></tr>}/><h2>Estado de zonas</h2><Table headers={['Zona','Estado','Disponibilidad','Acciones']} items={catalogs.zones} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.operationalStatus}</td><td>{x.isActive?'Activa':'Inactiva'}</td><td><button onClick={()=>request('/advanced/zones/'+x.id+'/state',token,{method:'PATCH',body:JSON.stringify({statusCode:'ACTIVE',isActive:true})}).then(load).catch(e=>notify(e.message))}>Activar</button><button onClick={()=>request('/advanced/zones/'+x.id+'/state',token,{method:'PATCH',body:JSON.stringify({statusCode:'MAINTENANCE',isActive:false})}).then(load).catch(e=>notify(e.message))}>Mantenimiento</button></td></tr>}/></>} 
 {module===9&&<><Table headers={['Regla','Zona','Umbral','Acciones']} items={items} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.zone}</td><td>{x.minimumMoisturePercent}% → {x.targetMoisturePercent}%</td><td><button onClick={()=>edit(x)}>Editar</button><button onClick={()=>run(`/advanced/rules/${x.id}/simulate`,'Simulación registrada; no se activaron equipos.')}>Simular</button></td></tr>}/><h2>Historial de evaluaciones</h2><Table headers={['Fecha','Regla','Tipo','Decisión']} items={secondary} render={x=><tr key={x.id}><td>{new Date(x.evaluatedAtUtc).toLocaleString()}</td><td>{x.rule}</td><td>{x.isSimulation?'Simulación':'Real'}</td><td>{x.decision}</td></tr>}/></>}
 {module===10&&<Table headers={['Programa','Zona','Próxima','Recurrencia','Acciones']} items={items} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.irrigationZone?.name}</td><td>{new Date(x.nextRunAtUtc).toLocaleString()}</td><td>{x.recurrence}</td><td><button onClick={()=>edit(x)}>Editar</button><button onClick={()=>remove(`/advanced/schedules/${x.id}`)}>Eliminar</button></td></tr>}/>} 
 {module===11&&<><Table headers={['Fuente','Tipo','Caudal','Estado','Acciones']} items={items} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.type}</td><td>{x.maximumFlowLitersMinute} L/min</td><td>{x.isActive?'Activa':'Inactiva'}</td><td><button onClick={()=>edit(x)}>Editar</button><button onClick={()=>remove(`/advanced/sources/${x.id}`)}>Eliminar</button></td></tr>}/><h2>Llenado automático</h2><Table headers={['Tanque','Fuente','Umbrales','Decisión']} items={secondary} render={x=><tr key={x.id}><td>{x.waterTank?.name}</td><td>{x.waterSource?.name}</td><td>{x.startAtPercent}% / {x.stopAtPercent}%</td><td>{x.lastDecision??'Pendiente'}</td></tr>}/></>}
 {module===12&&<><Table headers={['Panel/arreglo','Potencia','Cantidad','Acciones']} items={items} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.ratedPowerWatts} W</td><td>{x.panelCount}</td><td><button onClick={()=>{setForm({...empty[12],kind:'array',...x});setEditing(x.id)}}>Editar</button><button onClick={()=>remove(`/advanced/energy/arrays/${x.id}`)}>Eliminar</button></td></tr>}/><Table headers={['Batería/controlador','Estado','Capacidad / corriente','Acciones']} items={secondary} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.status}</td><td>{x.capacityWattHours?`${x.capacityWattHours} Wh`:`${x.ratedCurrentAmps} A`}</td><td><button onClick={()=>{setForm({...empty[12],kind:x.capacityWattHours?'battery':'controller',...x});setEditing(x.id)}}>Editar</button><button onClick={()=>remove(`/advanced/energy/${x.capacityWattHours?'batteries':'controllers'}/${x.id}`)}>Eliminar</button></td></tr>}/><h2>Historial de autonomía</h2><Table headers={['Fecha','Batería','Generación','Consumo','Autonomía']} items={tertiary.slice(0,100)} render={x=><tr key={x.capturedAtUtc}><td>{new Date(x.capturedAtUtc).toLocaleString()}</td><td>{x.batteryPercent}%</td><td>{x.generationWatts} W</td><td>{x.consumptionWatts} W</td><td>{x.autonomyHours==null?'—':`${Number(x.autonomyHours).toFixed(1)} h`}</td></tr>}/></>}
 {module===13&&<><Table headers={['Línea base','Zona','Litros','Umbral','Acciones']} items={items} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.irrigationZone?.name??'General'}</td><td>{x.litersPerEvent}</td><td>{x.anomalyThresholdPercent}%</td><td><button onClick={()=>edit(x)}>Editar</button><button onClick={()=>remove(`/advanced/efficiency/baselines/${x.id}`)}>Eliminar</button></td></tr>}/><h2>Eventos y anomalías</h2><Table headers={['Fecha','Zona','Consumo','Ahorro','Estado']} items={secondary} render={x=><tr key={x.id}><td>{new Date(x.recordedAtUtc).toLocaleDateString()}</td><td>{x.zone}</td><td>{x.volumeLiters} L</td><td>{x.savingLiters==null?'—':`${x.savingLiters.toFixed(1)} L`}</td><td>{x.isAnomaly?'Anómalo':'Normal'}</td></tr>}/></>}
 {module===14&&<><Table headers={['Orden','Tipo','Trabajo','Técnico','Compromiso','Estado','Acciones']} items={items} render={x=><tr key={x.id}><td>{x.number}</td><td>{x.kind}</td><td>{x.title}</td><td>{x.technicianName||'Sin asignar'}</td><td>{new Date(x.commitmentAtUtc).toLocaleDateString()}</td><td>{x.status}</td><td><button onClick={()=>edit(x)}>Editar</button><button onClick={()=>remove(`/advanced/work-orders/${x.id}`)}>Eliminar</button></td></tr>}/><h2>Historial por dispositivo</h2><Table headers={['Tipo','Equipo','Acción']} items={secondary} render={x=><tr key={`${x.type}-${x.id}`}><td>{x.type}</td><td>{x.name}</td><td><button onClick={()=>equipmentHistory(x)}>Ver historial</button></td></tr>}/>{tertiary?.plans&&<div className="am-model"><h3>Historial seleccionado</h3><p>Planes: {tertiary.plans.length} · Actividades: {tertiary.activities.length} · Incidencias: {tertiary.incidents.length}</p>{[...tertiary.plans,...tertiary.activities,...tertiary.incidents].map((x,i)=><code key={x.id??i}>{x.name??x.title} · {x.status}</code>)}</div>}</>}
 {module===15&&<><div className="am-toolbar"><button onClick={()=>summary('daily')}>Resumen diario</button><button onClick={()=>summary('weekly')}>Resumen semanal</button><button onClick={()=>run('/advanced/integrations/n8n/test','Prueba n8n registrada.')}>Probar n8n</button><button onClick={()=>run('/advanced/integrations/telegram/test','Prueba Telegram registrada.')}>Probar Telegram</button><button onClick={()=>run('/advanced/integrations/teams/test','Prueba Teams registrada.')}>Probar Teams</button></div><Table headers={['Regla','Tipo','Canales','Resúmenes','Acciones']} items={items} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.alertType} · {x.minimumSeverity}</td><td>{x.channels}</td><td>{x.dailySummary?'Diario ':''}{x.weeklySummary?'Semanal':''}</td><td><button onClick={()=>edit(x)}>Editar</button><button onClick={()=>remove(`/advanced/notification-rules/${x.id}`)}>Eliminar</button></td></tr>}/><h2>Historial n8n e integraciones</h2><Table headers={['Fecha','Integración','Operación','Estado']} items={secondary} render={x=><tr key={x.id}><td>{new Date(x.executedAtUtc).toLocaleString()}</td><td>{x.integration}</td><td>{x.operation}</td><td>{x.status}</td></tr>}/></>}
 {module===16&&<><div className="am-report-grid"><button onClick={()=>run('/advanced/integrations/powerbi/test','Prueba Power BI registrada.')}>Probar conexión Power BI</button>{['consumption','irrigation','maintenance','readings','alerts','iot','energy'].map(x=><button key={x} onClick={()=>download(x).catch(e=>notify(e.message))}>Descargar PDF · {x}</button>)}</div><section className="am-model"><h2>Modelo Power BI</h2><h3>Relaciones</h3>{items.relationships?.map(x=><code key={x}>{x}</code>)}<h3>Medidas DAX</h3>{Object.entries(items.dax??{}).map(([k,v])=><p key={k}><b>{k}</b><code>{v}</code></p>)}</section></>}
 {module===17&&<Configuration items={items} rules={secondary} token={token} notify={notify} reload={load}/>} 
 </div>
}

function Configuration({items,rules,token,notify,reload}){
 const keys=['SYSTEM_NAME','SYSTEM_TIMEZONE','DATE_FORMAT','N8N_WEBHOOK_URL','POWERBI_PUSH_URL','TELEGRAM_WEBHOOK_URL','TEAMS_WEBHOOK_URL'],existing=Object.fromEntries((items??[]).map(x=>[x.key,x]));
 const [values,setValues]=useState(()=>Object.fromEntries(keys.map(k=>[k,existing[k]?.value??({SYSTEM_NAME:'Sistema de Riego',SYSTEM_TIMEZONE:'America/Guatemala',DATE_FORMAT:'dd/MM/yyyy'}[k]??'')]))),[versions,setVersions]=useState([]),[selected,setSelected]=useState('');
 // La respuesta de parámetros es la única fuente que debe resincronizar el formulario.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>setValues(Object.fromEntries(keys.map(k=>[k,existing[k]?.value??({SYSTEM_NAME:'Sistema de Riego',SYSTEM_TIMEZONE:'America/Guatemala',DATE_FORMAT:'dd/MM/yyyy'}[k]??'')]))),[items]);
 const save=async()=>{for(const key of keys)await request(`/settings/${key}`,token,{method:'PUT',body:JSON.stringify({value:values[key]||'-',dataType:'text',category:key.includes('URL')?'Integraciones':'General',description:key.replaceAll('_',' '),isEditable:true})});notify('Configuración general e integraciones actualizadas.');reload()};
 const history=async rule=>{setSelected(rule.name);setVersions(await request(`/advanced/rules/${rule.id}/versions`,token))};
 return <><section className="am-config"><h2>Configuración general e integraciones</h2>{keys.map(k=><Field key={k} label={k}><input value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})}/></Field>)}<button onClick={()=>save().catch(e=>notify(e.message))}>Guardar configuración</button></section><h2>Versionado de reglas</h2><Table headers={['Regla','Estado','Última decisión','Versiones']} items={rules} render={x=><tr key={x.id}><td>{x.name}</td><td>{x.isEnabled?'Activa':'Inactiva'}</td><td>{x.lastDecision}</td><td><button onClick={()=>history(x).catch(e=>notify(e.message))}>Ver historial</button></td></tr>}/>{selected&&<><h3>Versiones · {selected}</h3><Table headers={['Versión','Fecha','Cambio','Usuario']} items={versions} render={x=><tr key={x.id}><td>v{x.version}</td><td>{new Date(x.changedAtUtc).toLocaleString()}</td><td>{x.changeReason}</td><td>{x.changedByEmail??'Sistema'}</td></tr>}/></>}</>
}
