/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState, type FormEvent } from 'react'
import { week3Api, type IoTRecord } from './week3Api'
import { askForm } from './dialogs'

// Debe coincidir con IoTTraceabilityController.InventoryStatuses: el servidor
// rechaza cualquier otro valor.
const INVENTORY_STATUSES=['Instalado','Disponible','Dañado','En mantenimiento']

type Named = IoTRecord & { id:string; name:string }
type Props={token:string;nodes:Named[];devices:Named[];canEdit:boolean;notify:(message:string)=>void}
const dateTimeLocal=()=>new Date().toISOString().slice(0,16)

export default function IoTTraceabilityPanel({token,nodes,devices,canEdit,notify}:Props){
 const [communication,setCommunication]=useState<IoTRecord>({}),[zones,setZones]=useState<Named[]>([]),[installations,setInstallations]=useState<IoTRecord[]>([]),[commands,setCommands]=useState<IoTRecord[]>([]),[firmware,setFirmware]=useState<IoTRecord[]>([]),[inventory,setInventory]=useState<IoTRecord[]>([])
 const [installation,setInstallation]=useState({deviceId:'',irrigationZoneId:'',location:'',installedAtUtc:dateTimeLocal(),installerName:'',removedAtUtc:null as string|null,notes:''})
 const [remote,setRemote]=useState({nodeId:'',commandType:'CAMBIAR_FRECUENCIA',payload:'{"intervalSeconds":60}',maximumAttempts:3})
 const [release,setRelease]=useState({nodeId:'',version:'',status:'Pendiente de hardware',appliedAtUtc:null as string|null,notes:''})
 const load=async()=>{const [m,z,i,c,f,v]=await Promise.all([week3Api.communication(token),week3Api.zones(token),week3Api.installations(token),week3Api.remoteConfigurations(token),week3Api.firmwareHistory(token),week3Api.inventory(token)]);setCommunication(m);setZones(z as Named[]);setInstallations(i);setCommands(c);setFirmware(f);setInventory(v);setInstallation(x=>({...x,deviceId:x.deviceId||devices[0]?.id||'',irrigationZoneId:x.irrigationZoneId||z[0]?.id as string||''}));setRemote(x=>({...x,nodeId:x.nodeId||nodes[0]?.id||''}));setRelease(x=>({...x,nodeId:x.nodeId||nodes[0]?.id||''}))}
 useEffect(()=>{load().catch(e=>notify(String(e)))},[])
 const saveInstallation=async(e:FormEvent)=>{e.preventDefault();await week3Api.createInstallation(token,{...installation,irrigationZoneId:installation.irrigationZoneId||null,installedAtUtc:new Date(installation.installedAtUtc).toISOString()});notify('Instalación registrada con responsable y asociación territorial.');await load()}
 const queue=async(e:FormEvent)=>{e.preventDefault();await week3Api.queueRemoteConfiguration(token,remote);notify('Configuración remota agregada a la cola de confirmación.');await load()}
 const register=async(e:FormEvent)=>{e.preventDefault();await week3Api.registerFirmware(token,release);notify('Versión de firmware registrada.');await load()}
 const editInventory=async(item:IoTRecord)=>{const answer=await askForm('Inventario del dispositivo',[{name:'owner',label:'Propietario o responsable',value:String(item.owner??''),required:false},{name:'status',label:'Estado',type:'select',options:INVENTORY_STATUSES,value:INVENTORY_STATUSES.includes(String(item.inventoryStatus))?String(item.inventoryStatus):'Instalado'},{name:'cost',label:'Costo de adquisición (GTQ)',type:'number',value:String(item.acquisitionCost??''),required:false}],{confirmLabel:'Guardar inventario'});if(!answer)return;const owner=answer.owner,status=answer.status,cost=answer.cost;await week3Api.updateInventory(token,String(item.id),{owner,inventoryStatus:status,purchaseDate:item.purchaseDate??null,warrantyUntil:item.warrantyUntil??null,acquisitionCost:cost?Number(cost):null,currency:'GTQ'});notify('Inventario actualizado.');await load()}
 return <section className="iot-traceability">
  <header><p className="w2-kicker">TRAZABILIDAD DE INFRAESTRUCTURA</p><h2>Instalación, configuración, firmware e inventario</h2><p>La evidencia operativa se conserva como historial; una actualización OTA solo se marca aplicada cuando existe confirmación real.</p></header>
  <div className="iot-trace-grid">
   <article className="iot-communication"><h3>Comunicación MQTT</h3><dl><div><dt>Protocolo</dt><dd>{String(communication.protocol??'MQTT')}</dd></div><div><dt>Broker</dt><dd>{String(communication.host??'localhost')}:{String(communication.port??1883)}</dd></div><div><dt>Autenticación</dt><dd>{String(communication.authentication??'Verificando')}</dd></div><div><dt>Clientes autorizados</dt><dd>{Array.isArray(communication.allowedClientIds)?communication.allowedClientIds.join(', '):'Sin datos'}</dd></div></dl><p>Los tópicos de telemetría, comandos y ACK se administran en el backend. Las credenciales están configuradas, pero sus secretos nunca se exponen en esta interfaz.</p><code>{String((communication.topics as IoTRecord|undefined)?.telemetryTopic??'granja/+/sensor/+/lectura')}</code></article>
   <article><h3>Historial de instalación</h3>{canEdit&&<form onSubmit={saveInstallation}><select required value={installation.deviceId} onChange={e=>setInstallation({...installation,deviceId:e.target.value})}>{devices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={installation.irrigationZoneId} onChange={e=>setInstallation({...installation,irrigationZoneId:e.target.value})}><option value="">Sin zona</option>{zones.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required placeholder="Ubicación exacta" value={installation.location} onChange={e=>setInstallation({...installation,location:e.target.value})}/><input required placeholder="Técnico instalador" value={installation.installerName} onChange={e=>setInstallation({...installation,installerName:e.target.value})}/><input type="datetime-local" value={installation.installedAtUtc} onChange={e=>setInstallation({...installation,installedAtUtc:e.target.value})}/><button>Registrar instalación</button></form>}<TraceList items={installations} primary="device" secondary="location" meta="installerName"/></article>
   <article><h3>Configuración remota</h3>{canEdit&&<form onSubmit={queue}><select required value={remote.nodeId} onChange={e=>setRemote({...remote,nodeId:e.target.value})}>{nodes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={remote.commandType} onChange={e=>setRemote({...remote,commandType:e.target.value})}><option>CAMBIAR_FRECUENCIA</option><option>CAMBIAR_LIMITES</option><option>REINICIAR</option></select><textarea value={remote.payload} onChange={e=>setRemote({...remote,payload:e.target.value})}/><button>Agregar a cola</button></form>}<TraceList items={commands} primary="node" secondary="commandType" meta="status"/></article>
   <article><h3>Registro de firmware</h3>{canEdit&&<form onSubmit={register}><select required value={release.nodeId} onChange={e=>setRelease({...release,nodeId:e.target.value})}>{nodes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required placeholder="Versión, ej. 2.1.0" value={release.version} onChange={e=>setRelease({...release,version:e.target.value})}/><select value={release.status} onChange={e=>setRelease({...release,status:e.target.value})}><option>Registrada</option><option>Pendiente de hardware</option><option>Aplicada</option></select><button>Registrar versión</button></form>}<TraceList items={firmware} primary="node" secondary="version" meta="status"/></article>
   <article><h3>Inventario IoT</h3><div className="iot-inventory-list">{inventory.map(x=><div key={String(x.id)}><b>{String(x.name)}</b><span>{String(x.inventoryStatus)} · {String(x.owner??'Sin responsable')}</span><small>{x.warrantyUntil?'Garantía '+String(x.warrantyUntil):'Garantía no registrada'} · {x.acquisitionCost?String(x.currency)+' '+String(x.acquisitionCost):'Costo pendiente'}</small>{canEdit&&<button onClick={()=>editInventory(x).catch(e=>notify(String(e)))}>Editar inventario</button>}</div>)}</div></article>
  </div>
 </section>
}
function TraceList({items,primary,secondary,meta}:{items:IoTRecord[];primary:string;secondary:string;meta:string}){return <div className="iot-trace-list">{items.length===0?<p>Sin registros todavía.</p>:items.slice(0,8).map(x=><div key={String(x.id)}><b>{String(x[primary]??'Registro')}</b><span>{String(x[secondary]??'')}</span><small>{String(x[meta]??'')}</small></div>)}</div>}



