import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './week2.css'
import './week2-polish.css'
import './week2-interactive.css'
import './catalog-edit.css'
import './water-theme.css'
import './week3-iot.css'
import './modules1to7.css'
import './modules7to10.css'
import './modules-nav.css'
import './sprint2.css'
import './gsapParallax'
import Week2App from './Week2App'
createRoot(document.getElementById('root')!).render(<StrictMode><Week2App /></StrictMode>)
