// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- TODO: retirar al completar el tipado heredado.
// @ts-nocheck
// TODO: tipar contratos heredados de API, props y estado antes de retirar esta supresión.
/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react'
import { operationsApi as api } from './modules7to10Api'
import Week14Analytics from './Week14Analytics'

const fmt=n=>Number(n??0).toLocaleString('es-GT',{maximumFractionDigits:1})
const when=x=>x?new Date(x).toLocaleString('es-GT'):'—'
function Head({module,title,copy,action}){return <div className="o-head"><div><p>MÓDULO {module}</p><h1>{title}</h1><span>{copy}</span></div>{action}</div>}
function Empty({children}){return <div className="o-empty">{children}</div>}

export function AutomationPanel({session,notify}){
 const token=session.accessToken,[rules,setRules]=useState([]),[active,setActive]=useState([]),[busy,setBusy]=useState(false)
 const load=()=>Promise.all([api.rules(token),api.active(token)]).then(([a,b])=>{setRules(a);setActive(b)})
 useEffect(()=>{load().catch(e=>notify(e.message))},[])
 const evaluate=async()=>{setBusy(true);try{const r=await api.evaluate(token);notify(`${r.results.length} reglas evaluadas.`);await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 const toggle=async r=>{try{await api.toggleRule(token,r.id,!r.isEnabled);notify('Regla actualizada.');await load()}catch(e){notify(e.message)}}
 const edit=async r=>{const minimum=prompt('Nuevo umbral mínimo',r.minimumMoisturePercent);const target=prompt('Nuevo umbral objetivo',r.targetMoisturePercent);const totp=prompt('Código TOTP de 6 dígitos');if(minimum===null||target===null||!totp)return;try{await api.updateRule(token,r.id,{irrigationZoneId:r.irrigationZoneId,cropWaterRequirementId:r.cropWaterRequirementId,name:r.name,minimumMoisturePercent:Number(minimum),targetMoisturePercent:Number(target),hysteresisPercent:r.hysteresisPercent,priority:r.priority,maximumDurationMinutes:r.maximumDurationMinutes,allowedFrom:r.allowedFrom,allowedUntil:r.allowedUntil,allowedDays:r.allowedDays,isEnabled:r.isEnabled},totp);notify('Umbrales actualizados con 2FA.');await load()}catch(e){notify(e.message)}}
 return <><Head module="7 · AUTOMATIZACIÓN" title="Motor de decisiones" copy="Umbrales, ventanas horarias, histéresis y pausas de seguridad para evitar activaciones innecesarias." action={<button className="o-primary" onClick={evaluate} disabled={busy}>{busy?'Evaluando…':'Evaluar ahora'}</button>}/>
 <div className="o-kpis"><article><b>{rules.filter(x=>x.isEnabled).length}</b><span>Reglas activas</span></article><article><b>{active.length}</b><span>Riegos en curso</span></article><article><b>{rules.filter(x=>x.suspendedUntilUtc&&new Date(x.suspendedUntilUtc)>new Date()).length}</b><span>Pausas manuales</span></article></div>
 <div className="o-rule-grid">{rules.map(r=><article key={r.id} className={r.isEnabled?'enabled':'disabled'}><header><div><small>PRIORIDAD {r.priority}</small><h2>{r.name}</h2><span>{r.zone}</span></div><button className="o-switch" aria-label={`${r.isEnabled?'Desactivar':'Activar'} ${r.name}`} onClick={()=>toggle(r)}><i/></button></header><div className="o-threshold"><span><b>{fmt(r.minimumMoisturePercent)}%</b>Mínimo</span><i/><span><b>{fmt(r.targetMoisturePercent)}%</b>Objetivo</span></div><dl><div><dt>Ventana</dt><dd>{r.allowedFrom}–{r.allowedUntil}</dd></div><div><dt>Máximo</dt><dd>{r.maximumDurationMinutes} min</dd></div><div><dt>Histéresis</dt><dd>{fmt(r.hysteresisPercent)}%</dd></div></dl><button className="o-secondary" onClick={()=>edit(r)}>Editar umbrales (2FA)</button><footer className={`o-decision ${r.lastDecision==='Regar'?'go':''}`}><b>{r.lastDecision}</b><span>{r.lastReason??'Sin evaluación'}</span></footer></article>)}</div>
 {active.length>0&&<section className="o-panel"><header><div><small>EJECUCIÓN</small><h2>Operaciones activas</h2></div></header>{active.map(x=><div className="o-row" key={x.id}><span className="o-pulse"/><b>{x.zone}</b><span>{x.mode}</span><em>{x.plannedDurationMinutes} min · {fmt(x.flowRateLitersMinute)} L/min</em></div>)}</section>}</>
}

export function WaterSupplyPanel({session,notify}){
 const token=session.accessToken,[items,setItems]=useState([]),[history,setHistory]=useState([]),[busy,setBusy]=useState(false)
 const load=()=>Promise.all([api.supply(token),api.supplyHistory(token)]).then(([a,b])=>{setItems(a);setHistory(b)})
 useEffect(()=>{load().catch(e=>notify(e.message))},[])
 const command=async(pump,start)=>{setBusy(true);try{const r=await api[start?'pumpStart':'pumpStop'](token,pump.id,start?'Abastecimiento autorizado desde el panel':'Parada autorizada desde el panel');notify(r.message);await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 const simulate=async tank=>{const next=Math.min(tank.capacityLiters,Number(tank.currentLevelLiters)+500);try{await api.tankLevel(token,tank.id,next,'Lectura de nivel simulada desde el panel');notify('Nivel del tanque actualizado.');await load()}catch(e){notify(e.message)}}
 return <><Head module="8 · BOMBA Y TANQUE" title="Abastecimiento protegido" copy="Nivel disponible, estado de bomba, descansos mínimos y bloqueos para una operación segura."/>
 <div className="o-tanks">{items.map(t=><article key={t.id}><div className="o-tank-visual"><div style={{height:`${Math.min(100,t.levelPercent)}%`}}/><strong>{fmt(t.levelPercent)}%</strong></div><div className="o-tank-info"><small>RESERVA PRINCIPAL</small><h2>{t.name}</h2><p><b>{fmt(t.currentLevelLiters)} L</b> de {fmt(t.capacityLiters)} L</p><div className="o-safety"><span>Mínimo {fmt(t.minimumSafePercent)}%</span><span>Máximo {fmt(t.maximumFillPercent)}%</span></div><button className="o-secondary" onClick={()=>simulate(t)}>Simular +500 L</button></div>{t.pumps.map(p=><div className={`o-pump ${p.isRunning?'running':''}`} key={p.id}><span className="o-pump-icon"><i/></span><div><small>BOMBA DE LLENADO</small><h3>{p.name}</h3><p>{p.isRunning?'Encendida desde '+when(p.startedAtUtc):`Última parada ${when(p.lastStoppedAtUtc)}`}</p></div><button disabled={busy} onClick={()=>command(p,!p.isRunning)}>{p.isRunning?'Detener':'Encender'}</button></div>)}</article>)}</div>
 <section className="o-panel"><header><div><small>HISTORIAL</small><h2>Ciclos de abastecimiento</h2></div></header>{history.length?history.slice(0,8).map(x=><div className="o-row" key={x.id}><span className={x.status==='En curso'?'o-pulse':'o-dot'}/><b>{x.pump}</b><span>{x.status}</span><em>{fmt(x.suppliedLiters)} L · {when(x.startedAtUtc)}</em></div>):<Empty>Sin ciclos registrados todavía.</Empty>}</section></>
}

export function ManualIrrigationPanel({session,notify}){
 const token=session.accessToken,[zones,setZones]=useState([]),[runs,setRuns]=useState([]),[busy,setBusy]=useState(false),[form,setForm]=useState({irrigationZoneId:'',durationMinutes:15,flowRateLitersMinute:12,reason:'Ajuste operativo autorizado',observations:''})
 const load=()=>Promise.all([api.zones(token),api.runs(token)]).then(([a,b])=>{setZones(a);setRuns(b);setForm(f=>({...f,irrigationZoneId:f.irrigationZoneId||a[0]?.id||''}))})
 useEffect(()=>{load().catch(e=>notify(e.message))},[]);const active=runs.filter(x=>['En curso','Esperando ACK','Cierre pendiente'].includes(x.status))
 const start=async e=>{e.preventDefault();setBusy(true);try{const totp=prompt('Código TOTP de 6 dígitos');if(!totp)return;const r=await api.startManual(token,{...form,durationMinutes:Number(form.durationMinutes),flowRateLitersMinute:Number(form.flowRateLitersMinute)},totp);notify(r.message);await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 const stop=async run=>{setBusy(true);try{const r=await api.stopManual(token,run.id,'Detención confirmada por el operador');notify(`${r.message} ${fmt(r.volumeLiters)} L.`);await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 const emergency=async()=>{const totp=prompt('Código TOTP de 6 dígitos para PARO TOTAL');if(!totp||!confirm('¿Cerrar todas las válvulas activas y suspender la automatización?'))return;setBusy(true);try{const r=await api.emergencyStop(token,totp);notify(r.message+' Afectados: '+r.affected+'.');await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 return <><Head module="9 · RIEGO MANUAL" title="Operación asistida" copy="Activaciones autorizadas, estados MQTT/ACK y coordinación con el modo automático." action={<button className="o-primary danger" onClick={emergency} disabled={busy}>PARO TOTAL</button>}/>
 <div className="o-manual-layout"><form className="o-manual-form" onSubmit={start}><small>NUEVA INTERVENCIÓN</small><h2>Programar riego manual</h2><label>Zona<select value={form.irrigationZoneId} onChange={e=>setForm({...form,irrigationZoneId:e.target.value})} required>{zones.map(x=><option key={x.id} value={x.id}>{x.name}{x.isRunning?' · EN CURSO':''}</option>)}</select></label><div><label>Duración<input type="number" min="1" max="120" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:e.target.value})}/><span>minutos</span></label><label>Caudal<input type="number" min="1" max="100" step="0.1" value={form.flowRateLitersMinute} onChange={e=>setForm({...form,flowRateLitersMinute:e.target.value})}/><span>L/min</span></label></div><label>Motivo<input value={form.reason} maxLength="300" onChange={e=>setForm({...form,reason:e.target.value})} required/></label><label>Observaciones<textarea value={form.observations} onChange={e=>setForm({...form,observations:e.target.value})}/></label><div className="o-estimate"><span>Consumo estimado</span><b>{fmt(Number(form.durationMinutes)*Number(form.flowRateLitersMinute))} L</b></div><button className="o-primary" disabled={busy||!form.irrigationZoneId}>Confirmar e iniciar</button></form>
 <section className="o-active-runs"><small>CONTROL DE ZONAS</small><h2>Riegos activos</h2>{active.length?active.map(x=><article key={x.id}><span className="o-pulse"/><div><b>{x.zone}</b><p>{x.reason}</p><small>{x.mode} · {x.status} · {x.plannedDurationMinutes} min · iniciado {when(x.startedAtUtc)}</small></div><button onClick={()=>stop(x)} disabled={busy}>Detener</button></article>):<Empty>No hay riegos activos. Las reglas automáticas conservan el control.</Empty>}</section></div>
 <section className="o-panel"><header><div><small>TRAZABILIDAD</small><h2>Intervenciones recientes</h2></div></header>{runs.slice(0,10).map(x=><div className="o-row" key={x.id}><span className={x.status==='En curso'?'o-pulse':'o-dot'}/><b>{x.zone}</b><span>{x.mode} · {x.status}</span><em>{fmt(x.estimatedLiters)} L planificados · {when(x.requestedAtUtc)}</em></div>)}</section></>
}

export function WaterOperationsPanel(props){
 return <Week14Analytics {...props}/>
}
export function LegacyWaterOperationsPanel({session,notify}){
 const token=session.accessToken,[days,setDays]=useState(30),[summary,setSummary]=useState(null),[events,setEvents]=useState([]),[search,setSearch]=useState('')
 const load=()=>Promise.all([api.summary(token,days),api.history(token,search?`?search=${encodeURIComponent(search)}`:'')]).then(([a,b])=>{setSummary(a);setEvents(b)})
 useEffect(()=>{load().catch(e=>notify(e.message))},[days]);const max=Math.max(1,...(summary?.daily??[]).map(x=>Number(x.volumeLiters)))
 const submit=e=>{e.preventDefault();load().catch(x=>notify(x.message))};const exportData=()=>api.exportCsv(token).then(()=>notify('Archivo CSV descargado.')).catch(e=>notify(e.message))
 return <><Head module="10 · CONSUMO E HISTORIAL" title="Bitácora hídrica" copy="Consumo consolidado por período y zona, eventos operativos con filtros y exportación CSV." action={<button className="o-primary" onClick={exportData}>Descargar CSV</button>}/>
 {summary&&<><div className="o-kpis o-consumption"><article><b>{fmt(summary.totalLiters)} L</b><span>Consumo total</span></article><article><b>{summary.eventCount}</b><span>Eventos de riego</span></article><article><b>{fmt(summary.averageLiters)} L</b><span>Promedio por evento</span></article><article><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 días</option><option value="30">30 días</option><option value="90">90 días</option></select><span>Período analizado</span></article></div><div className="o-consumption-grid"><section className="o-panel"><header><div><small>TENDENCIA DIARIA</small><h2>Litros utilizados</h2></div></header><div className="o-bars">{summary.daily.map(x=><div key={x.date}><span style={{height:`${Math.max(7,Number(x.volumeLiters)/max*100)}%`}} title={`${fmt(x.volumeLiters)} L`}/><small>{new Date(x.date).toLocaleDateString('es-GT',{day:'2-digit',month:'short'})}</small></div>)}</div></section><section className="o-panel"><header><div><small>POR ZONA</small><h2>Distribución del consumo</h2></div></header>{summary.byZone.map(x=><div className="o-zone-consumption" key={x.zone}><div><b>{x.zone}</b><span>{x.events} eventos</span></div><strong>{fmt(x.volumeLiters)} L</strong></div>)}</section></div></>}
 <section className="o-panel o-log"><header><div><small>BITÁCORA OPERATIVA</small><h2>Eventos del sistema</h2></div><form onSubmit={submit}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar detalle…"/><button>Buscar</button></form></header>{events.length?events.map(x=><div className="o-row" key={x.id}><span className={`o-event-dot ${x.severity?.toLowerCase()}`}/><b>{x.category}</b><span>{x.zone??'Sistema general'}<small>{x.detail}</small></span><em>{when(x.occurredAtUtc)}</em></div>):<Empty>No hay eventos para el filtro seleccionado.</Empty>}</section></>
}
