// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- TODO: retirar al completar el tipado heredado.
// @ts-nocheck
// TODO: tipar contratos heredados de API, props y estado antes de retirar esta supresión.
/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect,useMemo,useState } from 'react'
import { HubConnectionBuilder, LogLevel } from '@microsoft/signalr'
import { modulesApi as api } from './modulesApi'
const hubUrl=(import.meta.env.VITE_API_URL??`http://${window.location.hostname}:5080/api`).replace(/\/api\/?$/,String())+"/hubs/telemetry"
import './territory-management.css'
export { default as TerritoryManager } from './TerritoryManager'

const fmt=n=>Number(n??0).toLocaleString('es-GT',{maximumFractionDigits:1})
const date=x=>new Date(x).toLocaleString('es-GT',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})
const Head=({kicker,title,copy,action})=><div className="m-head"><div><p>{kicker}</p><h1>{title}</h1><span>{copy}</span></div>{action}</div>
const Load=()=> <div className="m-loading"><i/><span>Sincronizando datos del cultivo…</span></div>

export function OperationalDashboard({session,onNavigate,notify}){
 const [data,setData]=useState(null); const [tree,setTree]=useState([]); const load=()=>Promise.all([api.dashboard(session.accessToken),api.hierarchy(session.accessToken)]).then(([d,t])=>{setData(d);setTree(t)})
 useEffect(()=>{load().catch(e=>notify(e.message));const id=setInterval(()=>load().catch(()=>{}),30000);return()=>clearInterval(id)},[])
 useEffect(()=>{const connection=new HubConnectionBuilder().withUrl(hubUrl,{accessTokenFactory:()=>session.accessToken}).withAutomaticReconnect().configureLogging(LogLevel.Warning).build();connection.on('telemetryReadingReceived',()=>load().catch(()=>{}));connection.start().catch(e=>notify(e.message));return()=>{connection.stop().catch(()=>{})}},[session.accessToken])
 if(!data)return <Load/>; const readings=data.latestReadings??[]; const points=readings.slice().reverse().map((x,i)=>`${i*34+8},${100-Math.min(85,Math.max(10,Number(x.value)))}`).join(' ')
 return <><Head kicker="MÓDULO 1 · INICIO OPERATIVO" title={`Buen día, ${session.user.fullName.split(' ')[0]}`} copy="Visión integrada de agua, sensores, cultivos y actividad reciente." action={<button className="m-live" onClick={()=>load().catch(e=>notify(e.message))}><i/> Actualizar ahora</button>}/>
 <div className="m-kpis">{[["💧",`${fmt(data.averageMoisture)}%`,'Humedad media'],['◉',data.activeSensors,'Sensores activos'],['▦',data.activeZones,'Zonas de riego'],['🌱',data.activeCropCycles,'Ciclos de cultivo'],['⚠',data.invalidReadings,'Lecturas a revisar']].map(x=><article key={x[2]}><b>{x[0]}</b><div><strong>{x[1]}</strong><span>{x[2]}</span></div></article>)}</div>
 <div className="m-grid"><section className="m-panel m-water"><header><div><small>TELEMETRÍA</small><h2>Pulso hídrico del terreno</h2></div><button onClick={()=>onNavigate('telemetry')}>Ver lecturas →</button></header><div className="m-chart"><div className="m-chart-water"/><svg viewBox="0 0 400 120" preserveAspectRatio="none"><polyline points={points||'8,70 390,70'}/></svg><div className="m-chart-labels"><span>Lecturas recientes</span><b>{readings[0]?`${fmt(readings[0].value)} ${readings[0].unitSymbol??''}`:'Sin datos'}</b></div></div></section>
 <section className="m-panel"><header><div><small>MAPA PRODUCTIVO</small><h2>Jerarquía de la finca</h2></div><button onClick={()=>onNavigate('territory')}>Administrar →</button></header><div className="m-tree">{tree.map(c=><div key={c.id}><b>⌂ {c.name}</b>{c.farms.map(f=><span key={f.id}>↳ {f.name} · {f.blocks.reduce((n,b)=>n+b.sectors.reduce((a,s)=>a+s.zones.length,0),0)} zonas</span>)}</div>)}</div></section></div>
 <section className="m-panel m-activity"><header><div><small>TRAZABILIDAD</small><h2>Actividad reciente</h2></div></header>{data.recentActivity?.map((x,i)=><div className="m-event" key={`${x.occurredAtUtc}-${i}`}><i/><div><b>{x.type.replaceAll('_',' ')}</b><span>{x.detail}</span></div><time>{date(x.occurredAtUtc)}</time></div>)}</section></>
}

export function TerritoryManagerLegacy({session,notify}){
 const [tree,setTree]=useState([]); useEffect(()=>{api.hierarchy(session.accessToken).then(setTree).catch(e=>notify(e.message))},[])
 return <><Head kicker="MÓDULO 2 · DATOS MAESTROS" title="Territorio de riego" copy="Del centro universitario hasta cada zona instrumentada."/>
 <div className="m-territory-summary"><span>Centro</span><i/> <span>Finca</span><i/> <span>Bloque</span><i/> <span>Sector</span><i/> <span>Zona + sensor</span></div>
 {tree.map(c=><section className="m-farm" key={c.id}><header><div className="m-farm-icon">⌂</div><div><small>{c.code}</small><h2>{c.name}</h2><p>{c.location}</p></div></header>{c.farms.map(f=><div className="m-farm-body" key={f.id}><h3>💧 {f.name}</h3>{f.blocks.map(b=><article key={b.id}><div><small>{b.code} · {b.soilType??'Suelo sin clasificar'}</small><b>{b.name}</b><span>{fmt(b.areaHectares)} ha</span></div><div className="m-zone-grid">{b.sectors.flatMap(s=>s.zones.map(z=><button key={z.id}><i className={z.sensor?'on':''}/><strong>{z.name}</strong><span>{z.sensor??'Sin sensor principal'}</span><small>{z.status} · {fmt(z.areaHectares)} ha</small></button>))}</div></article>)}</div>)}</section>)}
 <p className="m-tip">La API permite registrar y activar centros, fincas, bloques, sectores y zonas. La vista presenta la relación completa y el sensor principal asignado.</p></>
}

export function TelemetryMonitor({session,notify}){
 const [items,setItems]=useState([]),[quality,setQuality]=useState(null),[busy,setBusy]=useState(false); const load=()=>Promise.all([api.telemetry(session.accessToken),api.quality(session.accessToken)]).then(([i,q])=>{setItems(i);setQuality(q)})
 useEffect(()=>{load().catch(e=>notify(e.message))},[]); useEffect(()=>{const connection=new HubConnectionBuilder().withUrl(hubUrl,{accessTokenFactory:()=>session.accessToken}).withAutomaticReconnect().configureLogging(LogLevel.Warning).build();connection.on('telemetryReadingReceived',reading=>{setItems(current=>[reading,...current.filter(x=>x.id!==reading.id)].slice(0,250));api.quality(session.accessToken).then(setQuality).catch(()=>{})});connection.start().catch(e=>notify(e.message));return()=>{connection.stop().catch(()=>{})}},[session.accessToken])
 const grouped=useMemo(()=>Object.values(items.reduce((a,x)=>({...a,[x.sensorId]:a[x.sensorId]??x}),{})),[items]); const graph=items.filter(x=>x.sensorName.toLowerCase().includes('humedad')).slice(0,18).reverse(); const pts=graph.map((x,i)=>`${i*24+6},${100-Number(x.value)}`).join(' ')
 return <><Head kicker="MÓDULO 5 · SENSORES Y LECTURAS" title="Telemetría del cultivo" copy="Recepción, validación, historial y calidad de los datos ambientales." action={<button className="m-primary" onClick={()=>{setBusy(true);load().catch(e=>notify(e.message)).finally(()=>setBusy(false))}} disabled={busy}>{busy?'Actualizando…':'Actualizar lecturas'}</button>}/>
 {quality&&<div className="m-quality"><article><strong>{quality.validPercent}%</strong><span>Datos válidos</span></article><article><strong>{quality.availabilityPercent}%</strong><span>Disponibilidad</span></article><article><strong>{quality.reportingSensors}/{quality.activeSensors}</strong><span>Sensores reportando</span></article><article><strong>{quality.invalid}</strong><span>Lecturas observadas</span></article></div>}
 <section className="m-panel m-telemetry"><header><div><small>EN TIEMPO REAL</small><h2>Condición actual</h2></div><span className="m-live"><i/> Conectado</span></header><div className="m-sensor-cards">{grouped.map(x=><article key={x.sensorId}><div><i className={x.isValid?'ok':'bad'}/><small>{x.zoneName??'Red general'}</small></div><h3>{x.sensorName}</h3><strong>{fmt(x.value)} <em>{x.unitSymbol}</em></strong><span>Batería {fmt(x.batteryPercent)}% · Señal {x.signalStrength} dBm</span></article>)}</div><div className="m-line"><svg viewBox="0 0 430 110" preserveAspectRatio="none"><polyline points={pts||'5,60 425,60'}/></svg></div></section>
 <section className="m-panel m-readings"><header><div><small>HISTORIAL</small><h2>Últimas lecturas recibidas</h2></div></header>{items.slice(0,12).map(x=><div key={x.id}><span className={x.isValid?'m-valid':'m-invalid'}>{x.isValid?'Válida':'Revisar'}</span><b>{x.sensorName}</b><strong>{fmt(x.value)} {x.unitSymbol}</strong><time>{date(x.capturedAtUtc)}</time></div>)}</section></>
}

export function AgronomyManager({session,notify}){
 const [crops,setCrops]=useState([]),[soils,setSoils]=useState([]),[requirements,setRequirements]=useState([]),[recs,setRecs]=useState([]); const load=()=>Promise.all([api.crops(session.accessToken),api.soils(session.accessToken),api.requirements(session.accessToken),api.recommendations(session.accessToken)]).then(([a,b,c,d])=>{setCrops(a);setSoils(b);setRequirements(c);setRecs(d)}); useEffect(()=>{load().catch(e=>notify(e.message))},[])
 return <><Head kicker="MÓDULO 6 · AGRONOMÍA" title="Decisiones explicables" copy="Necesidades hídricas por cultivo, etapa y suelo, conectadas con la humedad medida."/>
 <div className="m-rec-grid">{recs.map(r=><article className={`m-rec ${r.decision==='Regar'?'irrigate':''}`} key={r.cycleId}><small>{r.crop} · {r.zone}</small><h2>{r.decision}</h2><div><strong>{r.currentMoisture==null?'—':`${fmt(r.currentMoisture)}%`}</strong><span>Humedad actual</span></div><p>{r.explanation}</p><footer><b>{r.suggestedMinutes} min</b><span>{fmt(r.suggestedLiters)} L sugeridos</span></footer></article>)}</div>
 <div className="m-grid"><section className="m-panel"><header><div><small>CULTIVOS</small><h2>Etapas fenológicas</h2></div></header>{crops.map(c=><div className="m-crop" key={c.id}><b>🌱 {c.name}</b><small>{c.scientificName}</small><div>{c.stages.map(s=><span key={s.id}>{s.sequence}. {s.name}<em>{s.estimatedDays} días</em></span>)}</div></div>)}</section><section className="m-panel"><header><div><small>SUELO Y AGUA</small><h2>Parámetros configurados</h2></div></header>{soils.map(s=><div className="m-soil" key={s.id}><b>{s.name}</b><span>Capacidad de campo <strong>{fmt(s.fieldCapacityPercent)}%</strong></span><span>Saturación <strong>{fmt(s.saturationPercent)}%</strong></span><span>Infiltración <strong>{fmt(s.infiltrationMillimetersHour)} mm/h</strong></span></div>)}<p className="m-tip">{requirements.length} reglas hídricas activas relacionan el cultivo con la respuesta de riego.</p></section></div></>
}

export function CropPlanner({session,notify}){
 const [cycles,setCycles]=useState([]),[recs,setRecs]=useState([]); useEffect(()=>{Promise.all([api.cycles(session.accessToken),api.recommendations(session.accessToken)]).then(([a,b])=>{setCycles(a);setRecs(b)}).catch(e=>notify(e.message))},[])
 return <><Head kicker="MÓDULO 7 · PLANIFICACIÓN DE CULTIVOS" title="Calendario agrícola" copy="Ciclos, zonas asignadas, etapas actuales y fechas de cosecha."/><div className="m-cycle-grid">{cycles.map(c=>{const progress=Math.max(3,Math.min(100,(Date.now()-new Date(c.sowingDate))/(new Date(c.expectedHarvestDate)-new Date(c.sowingDate))*100));const rec=recs.find(r=>r.cycleId===c.id);return <article className="m-cycle" key={c.id}><header><span>{c.status}</span><small>{c.zone}</small></header><h2>{c.name}</h2><p>🌿 {c.crop} · etapa: <b>{c.currentStage}</b></p><div className="m-progress"><i style={{width:`${progress}%`}}/></div><div className="m-dates"><span><small>Siembra</small>{new Date(`${c.sowingDate}T12:00`).toLocaleDateString('es-GT')}</span><span><small>Cosecha prevista</small>{new Date(`${c.expectedHarvestDate}T12:00`).toLocaleDateString('es-GT')}</span></div><footer><span>{fmt(c.areaHectares)} ha · {c.plantCount.toLocaleString('es-GT')} plantas</span><b>{rec?.decision??'Evaluando'}</b></footer></article>})}</div><section className="m-panel m-calendar"><header><div><small>RUTA PRODUCTIVA</small><h2>Del sensor a la decisión</h2></div></header><div><span>Sensor mide</span><i>→</i><span>Datos se validan</span><i>→</i><span>Regla agronómica</span><i>→</i><span>Recomendación</span><i>→</i><span>Operador decide</span></div></section></>
}
