/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState, type FormEvent } from 'react'
import { week2Api, type AuthSession, type CatalogForm, type CatalogItem, type DeviceBrand, type DeviceModel, type Permission, type Role, type UserSummary } from './week2Api'
import { sprint2Api, type CropType } from './sprint2Api'

type Props = { session:AuthSession; notify:(message:string)=>void }
const kinds:Record<string,string>={SensorType:'Tipos de sensor',DeviceType:'Tipos de dispositivo',MeasurementUnit:'Unidades',OperationalStatus:'Estados',ValveType:'Tipos de válvula',PumpType:'Tipos de bomba',WaterSource:'Fuentes de agua',AlertType:'Tipos de alerta',SuspensionReason:'Motivos de suspensión',ReadingFrequency:'Frecuencias de lectura',CropType:'Tipos de cultivo'}
const blank:CatalogForm={code:'',name:'',description:'',symbol:'',isActive:true}

export function MasterCatalogManager({session,notify}:Props){
  const [kind,setKind]=useState('ValveType'),[items,setItems]=useState<CatalogItem[]>([]),[form,setForm]=useState<CatalogForm>(blank),[editing,setEditing]=useState<string>(),[brands,setBrands]=useState<DeviceBrand[]>([]),[models,setModels]=useState<DeviceModel[]>([]),[cropTypes,setCropTypes]=useState<CropType[]>([])
  const load=async()=>{ if(kind==='Brands'){setBrands(await week2Api.brands(session.accessToken));return} if(kind==='Models'){setModels(await week2Api.models(session.accessToken));return} if(kind==='CropType'){setCropTypes(await sprint2Api.cropTypes(session));return} setItems(await week2Api.catalogs(session.accessToken,kind)) }
  useEffect(()=>{setEditing(undefined);setForm(blank);load().catch(e=>notify(String(e)))},[kind])
  const submit=async(e:FormEvent)=>{e.preventDefault(); if(kind==='CropType') await sprint2Api.saveCropType(session,{code:form.code,name:form.name,isActive:form.isActive},editing); else if(editing) await week2Api.updateCatalog(session.accessToken,kind,editing,form); else await week2Api.createCatalog(session.accessToken,kind,form); notify('Catálogo guardado.');setForm(blank);setEditing(undefined);await load()}
  const remove=async(id:string)=>{await week2Api.deleteCatalog(session.accessToken,kind,id);notify('Registro eliminado.');await load()}
  const toggleCropType=async(item:CropType)=>{await sprint2Api.saveCropType(session,{code:item.code,name:item.name,isActive:!item.isActive},item.id);notify(item.isActive?'Tipo de cultivo desactivado.':'Tipo de cultivo activado.');await load()}
  const addBrand=async()=>{const code=prompt('Código de marca');const name=prompt('Nombre de marca');if(code&&name){await week2Api.createBrand(session.accessToken,{code,name,isActive:true});await load()}}
  const addModel=async()=>{const brand=brands[0]??(await week2Api.brands(session.accessToken))[0];const types=await week2Api.catalogs(session.accessToken,'DeviceType');const name=prompt('Nombre de modelo');const code=prompt('Código de modelo');if(brand&&types[0]&&name&&code){await week2Api.createModel(session.accessToken,{deviceBrandId:brand.id,deviceTypeId:types[0].id,code,name,isActive:true});await load()}}
  const editBrand=async(x:DeviceBrand)=>{const name=prompt('Nombre de marca',x.name);if(name){await week2Api.updateBrand(session.accessToken,x.id,{code:x.code,name,description:x.description,isActive:x.isActive});await load()}}
  const editModel=async(x:DeviceModel)=>{const name=prompt('Nombre de modelo',x.name);if(name){await week2Api.updateModel(session.accessToken,x.id,{deviceBrandId:x.deviceBrandId,deviceTypeId:x.deviceTypeId,code:x.code,name,description:x.description,isActive:x.isActive});await load()}}
  return <><header className="s2-title"><h1>Datos maestros</h1><p>Catálogos normalizados utilizados por la infraestructura de riego.</p></header><div className="s2-tabs">{[...Object.keys(kinds),'Brands','Models'].map(x=><button className={kind===x?'active':''} onClick={()=>setKind(x)} key={x}>{kinds[x]??(x==='Brands'?'Marcas':'Modelos')}</button>)}</div>
  {!['Brands','Models'].includes(kind)&&<><form className="s2-form" onSubmit={e=>submit(e).catch(x=>notify(String(x)))}><label>Código<input placeholder="Código" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></label><label>Nombre<input placeholder="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label>{kind!=='CropType'&&<><input placeholder="Descripción" value={form.description??''} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Símbolo" value={form.symbol??''} onChange={e=>setForm({...form,symbol:e.target.value})}/></>}<button>{editing?'Actualizar':'Agregar'}</button></form>{kind==='CropType'?<CropTypeTable items={cropTypes} edit={x=>{setEditing(x.id);setForm({code:x.code,name:x.name,description:'',symbol:'',isActive:x.isActive})}} toggle={x=>toggleCropType(x).catch(error=>notify(String(error)))}/>:<CatalogTable items={items} edit={x=>{setEditing(x.id);setForm({code:x.code,name:x.name,description:x.description,symbol:x.symbol,isActive:x.isActive})}} remove={id=>remove(id).catch(x=>notify(String(x)))}/>}</>}
  {kind==='Brands'&&<><button className="s2-primary" onClick={()=>addBrand().catch(x=>notify(String(x)))}>Agregar marca</button><div className="s2-grid">{brands.map(x=><article key={x.id}><h3>{x.name}</h3><code>{x.code}</code><p>{x.modelCount} modelos</p><button onClick={()=>editBrand(x).catch(e=>notify(String(e)))}>Editar</button><button onClick={()=>week2Api.deleteBrand(session.accessToken,x.id).then(load).catch(e=>notify(String(e)))}>Eliminar</button></article>)}</div></>}
  {kind==='Models'&&<><button className="s2-primary" onClick={()=>addModel().catch(x=>notify(String(x)))}>Agregar modelo</button><div className="s2-grid">{models.map(x=><article key={x.id}><h3>{x.brand} · {x.name}</h3><p>{x.deviceType}</p><code>{x.code}</code><button onClick={()=>editModel(x).catch(e=>notify(String(e)))}>Editar</button><button onClick={()=>week2Api.deleteModel(session.accessToken,x.id).then(load).catch(e=>notify(String(e)))}>Eliminar</button></article>)}</div></>}</>
}
function CropTypeTable({items,edit,toggle}:{items:CropType[];edit:(x:CropType)=>void;toggle:(x:CropType)=>void}){return <div className="s2-table"><table><thead><tr><th>Código</th><th>Nombre</th><th>Estado</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><code>{x.code}</code></td><td>{x.name}</td><td><span className={`s2-status ${x.isActive?'on':''}`}>{x.isActive?'Activo':'Inactivo'}</span></td><td><button onClick={()=>edit(x)}>Editar</button><button className={x.isActive?'danger':''} onClick={()=>toggle(x)}>{x.isActive?'Desactivar':'Activar'}</button></td></tr>)}</tbody></table></div>}
function CatalogTable({items,edit,remove}:{items:CatalogItem[];edit:(x:CatalogItem)=>void;remove:(id:string)=>void}){return <div className="s2-table"><table><thead><tr><th>Código</th><th>Nombre</th><th>Descripción</th><th>Estado</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><code>{x.code}</code></td><td>{x.name}</td><td>{x.description??'—'}</td><td>{x.isActive?'Activo':'Inactivo'}</td><td><button onClick={()=>edit(x)}>Editar</button><button className="danger" onClick={()=>remove(x.id)}>Eliminar</button></td></tr>)}</tbody></table></div>}

export function UserSecurityManager({session,notify}:Props){
  const [users,setUsers]=useState<UserSummary[]>([]),[roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([])
  const load=async()=>{const [u,r,p]=await Promise.all([week2Api.users(session.accessToken),week2Api.roles(session.accessToken),week2Api.permissions(session.accessToken)]);setUsers(u);setRoles(r);setPermissions(p)}
  useEffect(()=>{load().catch(e=>notify(String(e)))},[])
  const code=()=>prompt('Código de 6 dígitos de tu aplicación autenticadora')??''
  const toggle=async(role:Role,p:string)=>{const next=role.permissions.includes(p)?role.permissions.filter(x=>x!==p):[...role.permissions,p];await week2Api.setRolePermissions(session.accessToken,role.name,next,code());notify('Matriz actualizada.');await load()}
  const create=async()=>{const email=prompt('Correo del nuevo usuario');const fullName=prompt('Nombre completo');const password=prompt('Contraseña inicial');if(!email||!fullName||!password)return;await week2Api.createUser(session.accessToken,{email,fullName,password},code());notify('Usuario creado por el administrador.');await load()}
  return <><header className="s2-title"><h1>Usuarios, roles y permisos</h1><p>Las operaciones críticas requieren un código TOTP válido.</p><button className="s2-primary" onClick={()=>create().catch(x=>notify(String(x)))}>Crear usuario</button></header><div className="s2-table"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.fullName}<small>{u.email}</small></td><td><select value={u.roles[0]??''} onChange={e=>week2Api.setUserRoles(session.accessToken,u.id,[e.target.value],code()).then(load).catch(x=>notify(String(x)))}>{roles.map(r=><option key={r.name}>{r.name}</option>)}</select></td><td><select value={u.status} onChange={e=>week2Api.setUserStatus(session.accessToken,u.id,e.target.value,code()).then(load).catch(x=>notify(String(x)))}><option>Active</option><option>Blocked</option><option>Disabled</option></select></td></tr>)}</tbody></table></div><h2>Matriz rol × permiso</h2><div className="s2-table"><table><thead><tr><th>Permiso</th>{roles.map(r=><th key={r.name}>{r.name}</th>)}</tr></thead><tbody>{permissions.map(p=><tr key={p.code}><td><b>{p.code}</b><small>{p.description}</small></td>{roles.map(r=><td key={r.name}><input aria-label={`${r.name} ${p.code}`} type="checkbox" checked={r.permissions.includes(p.code)} onChange={()=>toggle(r,p.code).catch(x=>notify(String(x)))}/></td>)}</tr>)}</tbody></table></div></>
}

export function TwoFactorSetup({session,notify}:Props){const [enabled,setEnabled]=useState(false),[key,setKey]=useState(''),[code,setCode]=useState('');useEffect(()=>{week2Api.totpStatus(session.accessToken).then(x=>setEnabled(x.enabled)).catch(e=>notify(String(e)))},[]);const setup=async()=>{const x=await week2Api.totpSetup(session.accessToken);setKey(x.sharedKey)};const enable=async()=>{const x=await week2Api.totpEnable(session.accessToken,code);setEnabled(true);notify(`2FA activado. Guarda ${x.recoveryCodes.length} códigos de recuperación.`)};return <><header className="s2-title"><h1>Autenticación de dos factores</h1><p>Protege las operaciones críticas con TOTP estándar.</p></header><article className="s2-security"><h2>{enabled?'2FA está activo':'Configura tu autenticador'}</h2>{!key&&!enabled&&<button onClick={()=>setup().catch(e=>notify(String(e)))}>Generar clave</button>}{key&&<><p>Agrega esta clave en tu aplicación autenticadora:</p><code>{key}</code><input inputMode="numeric" maxLength={6} placeholder="Código de 6 dígitos" value={code} onChange={e=>setCode(e.target.value)}/><button onClick={()=>enable().catch(e=>notify(String(e)))}>Confirmar y activar</button></>}</article></>}
