/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import interactionPlugin from '@fullcalendar/interaction'
import type { AuthSession } from './week2Api'
import { sprint2Api, type Crop, type CropType, type Cycle, type Soil, type Stage, type Zone } from './sprint2Api'

type Props={session:AuthSession;notify:(message:string)=>void}
const today=()=>new Date().toISOString().slice(0,10)

export function AgronomyManager({session,notify}:Props){
 const [soils,setSoils]=useState<Soil[]>([]),[types,setTypes]=useState<CropType[]>([]),[crops,setCrops]=useState<Crop[]>([]),[soilId,setSoilId]=useState<string>(),[cropId,setCropId]=useState<string>(),[stageId,setStageId]=useState<string>()
 const [soil,setSoil]=useState({code:'',name:'',fieldCapacityPercent:30,saturationPercent:50,infiltrationMillimetersHour:10,description:'',isActive:true})
 const [crop,setCrop]=useState({cropTypeId:'',code:'',name:'',scientificName:'',description:'',isActive:true})
 const [stage,setStage]=useState({cropId:'',name:'',sequence:1,estimatedDays:14,description:''})
 const load=async()=>{const [s,t,c]=await Promise.all([sprint2Api.soils(session),sprint2Api.cropTypes(session),sprint2Api.crops(session)]);const activeTypes=t.filter(x=>x.isActive);setSoils(s);setTypes(t);setCrops(c);setCrop(x=>({...x,cropTypeId:activeTypes.some(y=>y.id===x.cropTypeId)?x.cropTypeId:activeTypes[0]?.id??''}));if(!stage.cropId&&c[0])setStage(x=>({...x,cropId:c[0].id}))}
 useEffect(()=>{load().catch(e=>notify(String(e)))},[])
 const saveSoil=async(e:FormEvent)=>{e.preventDefault();await sprint2Api.saveSoil(session,soil,soilId);setSoilId(undefined);setSoil({code:'',name:'',fieldCapacityPercent:30,saturationPercent:50,infiltrationMillimetersHour:10,description:'',isActive:true});notify('Suelo guardado.');await load()}
 const saveCrop=async(e:FormEvent)=>{e.preventDefault();await sprint2Api.saveCrop(session,crop,cropId);setCropId(undefined);setCrop({...crop,code:'',name:'',scientificName:'',description:''});notify('Cultivo guardado.');await load()}
 const saveStage=async(e:FormEvent)=>{e.preventDefault();await sprint2Api.saveStage(session,stage,stageId);setStageId(undefined);setStage({...stage,name:'',description:''});notify('Etapa guardada.');await load()}
 return <><header className="s2-title"><h1>Gestión agronómica</h1><p>Suelos, cultivos y etapas fenológicas con validaciones de dependencia.</p></header><section className="s2-panel"><h2>Suelos</h2><form className="s2-form" onSubmit={e=>saveSoil(e).catch(x=>notify(String(x)))}><label>Código<input placeholder="Ej. FRANCO" value={soil.code} onChange={e=>setSoil({...soil,code:e.target.value})} required/></label><label>Nombre<input placeholder="Nombre del suelo" value={soil.name} onChange={e=>setSoil({...soil,name:e.target.value})} required/></label><label>Capacidad de campo (%)<input type="number" min="0" max="100" value={soil.fieldCapacityPercent} onChange={e=>setSoil({...soil,fieldCapacityPercent:+e.target.value})}/></label><label>Saturación (%)<input type="number" min="0" max="100" value={soil.saturationPercent} onChange={e=>setSoil({...soil,saturationPercent:+e.target.value})}/></label><label>Infiltración (mm/h)<input type="number" min="0" step="0.1" value={soil.infiltrationMillimetersHour} onChange={e=>setSoil({...soil,infiltrationMillimetersHour:+e.target.value})}/></label><button>{soilId?'Actualizar':'Agregar'}</button></form><div className="s2-grid">{soils.map(x=><article key={x.id}><h3>{x.name}</h3><p>Campo {x.fieldCapacityPercent}% · Saturación {x.saturationPercent}%</p><button onClick={()=>{setSoilId(x.id);setSoil({...x,description:x.description??''})}}>Editar</button><button className="danger" onClick={()=>sprint2Api.deleteSoil(session,x.id).then(load).catch(e=>notify(String(e)))}>Eliminar</button></article>)}</div></section>
 <section className="s2-panel"><h2>Cultivos</h2><form className="s2-form" onSubmit={e=>saveCrop(e).catch(x=>notify(String(x)))}><label>Tipo de cultivo<select value={crop.cropTypeId} onChange={e=>setCrop({...crop,cropTypeId:e.target.value})} required>{types.filter(x=>x.isActive).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><input placeholder="Código" value={crop.code} onChange={e=>setCrop({...crop,code:e.target.value})} required/><input placeholder="Nombre" value={crop.name} onChange={e=>setCrop({...crop,name:e.target.value})} required/><input placeholder="Nombre científico" value={crop.scientificName} onChange={e=>setCrop({...crop,scientificName:e.target.value})}/><button>{cropId?'Actualizar':'Agregar'}</button></form><div className="s2-grid">{crops.map(x=><article key={x.id}><h3>{x.name}</h3><i>{x.scientificName}</i><p>{x.cropType} · {x.stages.length} etapas</p><button onClick={()=>{setCropId(x.id);setCrop({cropTypeId:x.cropTypeId,code:x.code,name:x.name,scientificName:x.scientificName??'',description:x.description??'',isActive:x.isActive})}}>Editar</button><button className="danger" onClick={()=>sprint2Api.deleteCrop(session,x.id).then(load).catch(e=>notify(String(e)))}>Eliminar</button></article>)}</div></section>
 <section className="s2-panel"><h2>Etapas fenológicas</h2><form className="s2-form" onSubmit={e=>saveStage(e).catch(x=>notify(String(x)))}><select value={stage.cropId} onChange={e=>setStage({...stage,cropId:e.target.value})}>{crops.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input placeholder="Nombre" value={stage.name} onChange={e=>setStage({...stage,name:e.target.value})} required/><input type="number" min="1" title="Secuencia" value={stage.sequence} onChange={e=>setStage({...stage,sequence:+e.target.value})}/><input type="number" min="1" title="Días estimados" value={stage.estimatedDays} onChange={e=>setStage({...stage,estimatedDays:+e.target.value})}/><button>{stageId?'Actualizar':'Agregar'}</button></form><div className="s2-grid">{crops.flatMap(c=>c.stages.map(x=>({...x,cropId:c.id,crop:c.name}))).map(x=><article key={x.id}><h3>{x.crop} · {x.name}</h3><p>Etapa {x.sequence} · {x.estimatedDays} días</p><button onClick={()=>{setStageId(x.id);setStage({cropId:x.cropId,name:x.name,sequence:x.sequence,estimatedDays:x.estimatedDays,description:x.description??''})}}>Editar</button><button className="danger" onClick={()=>sprint2Api.deleteStage(session,x.id).then(load).catch(e=>notify(String(e)))}>Eliminar</button></article>)}</div></section></>
}

export function CropPlanner({session,notify}:Props){
 const [cycles,setCycles]=useState<Cycle[]>([]),[crops,setCrops]=useState<Crop[]>([]),[zones,setZones]=useState<Zone[]>([]),[events,setEvents]=useState<Awaited<ReturnType<typeof sprint2Api.calendar>>>([]),[alerts,setAlerts]=useState<Awaited<ReturnType<typeof sprint2Api.alerts>>>([]),[editing,setEditing]=useState<string>()
 const [form,setForm]=useState({cropId:'',irrigationZoneId:'',currentStageId:null as string|null,name:'',sowingDate:today(),expectedHarvestDate:today(),actualHarvestDate:null as string|null,areaHectares:1,plantCount:0,status:'Planificado',notes:''})
 const load=async()=>{const [cy,cr,z,ev,al]=await Promise.all([sprint2Api.cycles(session),sprint2Api.crops(session),sprint2Api.zones(session),sprint2Api.calendar(session),sprint2Api.alerts(session)]);setCycles(cy);setCrops(cr);setZones(z);setEvents(ev);setAlerts(al);setForm(x=>({...x,cropId:x.cropId||cr[0]?.id||'',irrigationZoneId:x.irrigationZoneId||z[0]?.id||''}))}
 useEffect(()=>{load().catch(e=>notify(String(e)))},[])
 const stages=useMemo(()=>crops.find(x=>x.id===form.cropId)?.stages??[],[crops,form.cropId])
 const save=async(e:FormEvent)=>{e.preventDefault();await sprint2Api.saveCycle(session,form,editing);setEditing(undefined);setForm({...form,name:'',currentStageId:null});notify('Ciclo guardado.');await load()}
 const edit=(x:Cycle)=>{setEditing(x.id);setForm({cropId:x.cropId,irrigationZoneId:x.irrigationZoneId,currentStageId:x.currentStageId??null,name:x.name,sowingDate:x.sowingDate,expectedHarvestDate:x.expectedHarvestDate,actualHarvestDate:x.actualHarvestDate??null,areaHectares:x.areaHectares,plantCount:x.plantCount,status:x.status,notes:x.notes??''})}
 return <><header className="s2-title"><h1>Planificación de cultivos</h1><p>Calendario operativo, control de solapamientos y alertas de cosecha.</p></header>{alerts.length>0&&<div className="s2-alerts">{alerts.map(x=><span key={x.id} className={x.daysRemaining<0?'late':''}>{x.severity}: {x.name} · {x.expectedHarvestDate}</span>)}</div>}<div className="s2-calendar"><FullCalendar plugins={[dayGridPlugin,interactionPlugin]} initialView="dayGridMonth" locale="es" height="auto" events={events}/></div><section className="s2-panel"><h2>{editing?'Editar ciclo':'Nuevo ciclo'}</h2><form className="s2-cycle-form" onSubmit={e=>save(e).catch(x=>notify(String(x)))}><label>Cultivo<select value={form.cropId} onChange={e=>setForm({...form,cropId:e.target.value,currentStageId:null})}>{crops.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Zona<select value={form.irrigationZoneId} onChange={e=>setForm({...form,irrigationZoneId:e.target.value})}>{zones.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Etapa<select value={form.currentStageId??''} onChange={e=>setForm({...form,currentStageId:e.target.value||null})}><option value="">Sin etapa</option>{stages.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Siembra<input type="date" value={form.sowingDate} onChange={e=>setForm({...form,sowingDate:e.target.value})}/></label><label>Cosecha<input type="date" value={form.expectedHarvestDate} onChange={e=>setForm({...form,expectedHarvestDate:e.target.value})}/></label><label>Área (ha)<input type="number" min="0.01" step="0.01" value={form.areaHectares} onChange={e=>setForm({...form,areaHectares:+e.target.value})}/></label><label>Plantas<input type="number" min="0" value={form.plantCount} onChange={e=>setForm({...form,plantCount:+e.target.value})}/></label><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Planificado</option><option>Activo</option><option>Finalizado</option></select></label><button>{editing?'Guardar cambios':'Crear ciclo'}</button></form><div className="s2-grid">{cycles.map(x=><article key={x.id}><h3>{x.name}</h3><p>{x.crop} · {x.zone}</p><small>{x.sowingDate} → {x.expectedHarvestDate} · {x.currentStage}</small><button onClick={()=>edit(x)}>Editar</button><button className="danger" onClick={()=>sprint2Api.deleteCycle(session,x.id).then(load).catch(e=>notify(String(e)))}>Eliminar</button></article>)}</div></section></>
}
