// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- TODO: retirar al completar el tipado heredado.
// @ts-nocheck
// TODO: tipar contratos heredados de API, props y estado antes de retirar esta supresión.
/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect,useState } from 'react'
import { modulesApi as api } from './modulesApi'
import './territory-management.css'

const labels={centers:'Centro',farms:'Finca',blocks:'Bloque',sectors:'Sector',zones:'Zona'}
const fmt=value=>Number(value??0).toLocaleString('es-GT',{maximumFractionDigits:2})
const Head=({action})=><div className="m-head"><div><p>MÓDULO 2 · DATOS MAESTROS</p><h1>Territorio de riego</h1><span>Registra y administra la estructura desde el centro universitario hasta cada zona instrumentada.</span></div>{action}</div>
const emptyForm=(kind,data={centers:[],farms:[],blocks:[],sectors:[]},extra={soils:[],statuses:[],sensors:[],devices:[]})=>{
 const base={code:'',name:'',isActive:true}
 if(kind==='centers')return {...base,location:'',contact:''}
 if(kind==='farms')return {...base,universityCenterId:data.centers.find(x=>x.isActive)?.id??'',location:'',latitude:'',longitude:''}
 if(kind==='blocks')return {...base,farmId:data.farms.find(x=>x.isActive)?.id??'',soilTypeId:extra.soils.find(x=>x.isActive)?.id??'',areaHectares:'1',description:''}
 if(kind==='sectors')return {...base,farmBlockId:data.blocks.find(x=>x.isActive)?.id??'',areaHectares:'0.5',slopePercent:'0',boundaryGeoJson:''}
 return {...base,irrigationSectorId:data.sectors.find(x=>x.isActive)?.id??'',operationalStatusId:extra.statuses.find(x=>x.code==='ACTIVE')?.id??extra.statuses.find(x=>x.isActive)?.id??'',primarySensorId:'',sensorIds:[],valveDeviceIds:[],areaHectares:'0.25',latitude:'',longitude:'',boundaryGeoJson:''}
}

export default function TerritoryManager({session,notify}){
 const token=session.accessToken,canManage=session.user.roles.some(x=>x==='Administrador'||x==='Tecnico')
 const [tree,setTree]=useState([]),[kind,setKind]=useState('centers'),[inventory,setInventory]=useState({centers:[],farms:[],blocks:[],sectors:[],zones:[]}),[extra,setExtra]=useState({soils:[],statuses:[],sensors:[],devices:[]}),[form,setForm]=useState(emptyForm('centers')),[showManager,setShowManager]=useState(true),[busy,setBusy]=useState(false),[editingId,setEditingId]=useState(null)
 const load=async()=>{const [hierarchy,centers,farms,blocks,sectors,zones,soils,statuses,sensors,devices]=await Promise.all([api.hierarchy(token),api.centers(token),api.farms(token),api.blocks(token),api.sectors(token),api.zones(token),api.soils(token),api.catalogs(token,'OperationalStatus'),api.sensors(token),api.devices(token)]);const data={centers,farms,blocks,sectors,zones},more={soils,statuses,sensors,devices};setTree(hierarchy);setInventory(data);setExtra(more);return {data,more}}
 useEffect(()=>{load().then(x=>setForm(emptyForm('centers',x.data,x.more))).catch(e=>notify(e.message))},[])
 const choose=value=>{setKind(value);setEditingId(null);setForm(emptyForm(value,inventory,extra))},update=(key,value)=>setForm({...form,[key]:value}),nullable=value=>value===''?null:value,numberOrNull=value=>value===''?null:Number(value)
 const payload=()=>{
  if(kind==='centers')return {code:form.code,name:form.name,location:nullable(form.location),contact:nullable(form.contact),isActive:form.isActive}
  if(kind==='farms')return {universityCenterId:form.universityCenterId,code:form.code,name:form.name,location:nullable(form.location),latitude:numberOrNull(form.latitude),longitude:numberOrNull(form.longitude),isActive:form.isActive}
  if(kind==='blocks')return {farmId:form.farmId,soilTypeId:nullable(form.soilTypeId),code:form.code,name:form.name,areaHectares:Number(form.areaHectares),description:nullable(form.description),isActive:form.isActive}
  if(kind==='sectors')return {farmBlockId:form.farmBlockId,code:form.code,name:form.name,areaHectares:Number(form.areaHectares),slopePercent:Number(form.slopePercent),isActive:form.isActive,boundaryGeoJson:nullable(form.boundaryGeoJson)}
  return {irrigationSectorId:form.irrigationSectorId,code:form.code,name:form.name,areaHectares:Number(form.areaHectares),operationalStatusId:form.operationalStatusId,primarySensorId:nullable(form.primarySensorId),sensorIds:form.sensorIds,valveDeviceId:form.valveDeviceIds[0]??null,valveDeviceIds:form.valveDeviceIds,latitude:numberOrNull(form.latitude),longitude:numberOrNull(form.longitude),isActive:form.isActive,boundaryGeoJson:nullable(form.boundaryGeoJson)}
 }
 const submit=async event=>{event.preventDefault();setBusy(true);const wasEditing=Boolean(editingId);try{if(wasEditing)await api.updateTerritory(token,kind,editingId,payload());else await api.createTerritory(token,kind,payload());const state=await load();setEditingId(null);setForm(emptyForm(kind,state.data,state.more));notify(`${labels[kind]} ${wasEditing?'actualizado':'registrado'} correctamente.`)}catch(error){notify(error.message)}finally{setBusy(false)}}
 const toggle=async item=>{setBusy(true);try{await api.toggleTerritory(token,kind,item.id);const state=await load();setEditingId(null);setForm(emptyForm(kind,state.data,state.more));notify(`${labels[kind]} ${item.isActive?'desactivado':'activado'}.`)}catch(error){notify(error.message)}finally{setBusy(false)}}
 const relation=item=>item.center??item.farm??item.block??item.sector??item.location??'Nivel raíz'
 const edit=item=>{setEditingId(item.id);const base={code:item.code,name:item.name,isActive:item.isActive};if(kind==='centers')setForm({...base,location:item.location??'',contact:item.contact??''});else if(kind==='farms')setForm({...base,universityCenterId:item.universityCenterId,location:item.location??'',latitude:item.latitude??'',longitude:item.longitude??''});else if(kind==='blocks')setForm({...base,farmId:item.farmId,soilTypeId:item.soilTypeId??'',areaHectares:item.areaHectares,description:item.description??''});else if(kind==='sectors')setForm({...base,farmBlockId:item.farmBlockId,areaHectares:item.areaHectares,slopePercent:item.slopePercent,boundaryGeoJson:item.boundaryGeoJson??''});else setForm({...base,irrigationSectorId:item.irrigationSectorId,operationalStatusId:item.operationalStatusId,primarySensorId:item.primarySensorId??'',sensorIds:item.sensors?.map(x=>x.sensorId)??[],valveDeviceIds:item.valves?.map(x=>x.deviceId)??[],areaHectares:item.areaHectares,latitude:item.latitude??'',longitude:item.longitude??'',boundaryGeoJson:item.boundaryGeoJson??''});window.scrollTo({top:0,behavior:'smooth'})}
 const cancelEdit=()=>{setEditingId(null);setForm(emptyForm(kind,inventory,extra))}
 const common=<><label>Código<input value={form.code} maxLength="30" onChange={e=>update('code',e.target.value)} required/></label><label>Nombre<input value={form.name} onChange={e=>update('name',e.target.value)} required/></label></>
 const fields=<div className="tm-fields">{common}
  {kind==='centers'&&<><label className="wide">Ubicación<input value={form.location} onChange={e=>update('location',e.target.value)}/></label><label className="wide">Contacto<input value={form.contact} onChange={e=>update('contact',e.target.value)}/></label></>}
  {kind==='farms'&&<><label className="wide">Centro<select value={form.universityCenterId} onChange={e=>update('universityCenterId',e.target.value)} required>{inventory.centers.filter(x=>x.isActive||x.id===form.universityCenterId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="wide">Ubicación<input value={form.location} onChange={e=>update('location',e.target.value)}/></label><label>Latitud<input type="number" step="0.0000001" value={form.latitude} onChange={e=>update('latitude',e.target.value)}/></label><label>Longitud<input type="number" step="0.0000001" value={form.longitude} onChange={e=>update('longitude',e.target.value)}/></label><label className="wide">Polígono GeoJSON<textarea rows="5" value={form.boundaryGeoJson} onChange={e=>update('boundaryGeoJson',e.target.value)} placeholder='{"type":"Polygon","coordinates":[...]}'/></label></>}
  {kind==='blocks'&&<><label className="wide">Finca<select value={form.farmId} onChange={e=>update('farmId',e.target.value)} required>{inventory.farms.filter(x=>x.isActive||x.id===form.farmId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Tipo de suelo<select value={form.soilTypeId} onChange={e=>update('soilTypeId',e.target.value)}><option value="">Sin clasificar</option>{extra.soils.filter(x=>x.isActive||x.id===form.soilTypeId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Área (ha)<input type="number" min="0.01" step="0.01" value={form.areaHectares} onChange={e=>update('areaHectares',e.target.value)} required/></label><label className="wide">Descripción<textarea value={form.description} onChange={e=>update('description',e.target.value)}/></label></>}
  {kind==='sectors'&&<><label className="wide">Bloque<select value={form.farmBlockId} onChange={e=>update('farmBlockId',e.target.value)} required>{inventory.blocks.filter(x=>x.isActive||x.id===form.farmBlockId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Área (ha)<input type="number" min="0.01" step="0.01" value={form.areaHectares} onChange={e=>update('areaHectares',e.target.value)} required/></label><label>Pendiente (%)<input type="number" min="0" step="0.1" value={form.slopePercent} onChange={e=>update('slopePercent',e.target.value)} required/></label><label className="wide">Polígono GeoJSON<textarea rows="5" value={form.boundaryGeoJson} onChange={e=>update('boundaryGeoJson',e.target.value)} placeholder='{"type":"Polygon","coordinates":[...]}'/></label></>}
  {kind==='zones'&&<><label className="wide">Sector<select value={form.irrigationSectorId} onChange={e=>update('irrigationSectorId',e.target.value)} required>{inventory.sectors.filter(x=>x.isActive||x.id===form.irrigationSectorId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Estado operativo<select value={form.operationalStatusId} onChange={e=>update('operationalStatusId',e.target.value)} required>{extra.statuses.filter(x=>x.isActive||x.id===form.operationalStatusId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Sensor principal<select value={form.primarySensorId} onChange={e=>update('primarySensorId',e.target.value)}><option value="">Sin sensor principal</option>{extra.sensors.filter(x=>x.isActive||x.id===form.primarySensorId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Sensores asignados<select multiple value={form.sensorIds} onChange={e=>update('sensorIds',Array.from(e.target.selectedOptions,x=>x.value))}>{extra.sensors.filter(x=>x.isActive||form.sensorIds.includes(x.id)).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Válvulas asignadas<select multiple value={form.valveDeviceIds} onChange={e=>update('valveDeviceIds',Array.from(e.target.selectedOptions,x=>x.value))}>{extra.devices.filter(x=>x.isActive||form.valveDeviceIds.includes(x.id)).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Área (ha)<input type="number" min="0.01" step="0.01" value={form.areaHectares} onChange={e=>update('areaHectares',e.target.value)} required/></label><label>Latitud<input type="number" step="0.0000001" value={form.latitude} onChange={e=>update('latitude',e.target.value)}/></label><label>Longitud<input type="number" step="0.0000001" value={form.longitude} onChange={e=>update('longitude',e.target.value)}/></label><label className="wide">Polígono GeoJSON<textarea rows="5" value={form.boundaryGeoJson} onChange={e=>update('boundaryGeoJson',e.target.value)} placeholder='{"type":"Polygon","coordinates":[...]}'/></label></>}
  <label className="tm-check wide"><input type="checkbox" checked={form.isActive} onChange={e=>update('isActive',e.target.checked)}/> Registro activo</label></div>
 return <><Head action={canManage&&<button className="m-primary" onClick={()=>setShowManager(!showManager)}>{showManager?'Ocultar gestión':'Administrar territorio'}</button>}/>
  <div className="m-territory-summary"><span>Centro</span><i/><span>Finca</span><i/><span>Bloque</span><i/><span>Sector</span><i/><span>Zona + sensor</span></div>
  {canManage&&showManager&&<section className="tm-panel"><header><div><h2>Gestión territorial</h2><p>Crea, modifica, activa o desactiva los registros de cada nivel.</p></div></header><div className="tm-tabs">{Object.entries(labels).map(([value,label])=><button type="button" className={kind===value?'active':''} onClick={()=>choose(value)} key={value}>{label}</button>)}</div><div className="tm-layout"><form className="tm-form" onSubmit={submit}><h3>{editingId?'Modificar':'Registrar'} {labels[kind].toLowerCase()}</h3>{fields}<div className="tm-form-actions"><button disabled={busy}>{busy?'Guardando…':editingId?'Guardar cambios':`Guardar ${labels[kind].toLowerCase()}`}</button>{editingId&&<button type="button" className="cancel" disabled={busy} onClick={cancelEdit}>Cancelar edición</button>}</div></form><div className="tm-list"><h3>Registros existentes</h3><div className="tm-items">{inventory[kind].map(item=><div className="tm-item" key={item.id}><div><b>{item.code} · {item.name}</b><small>{relation(item)} · {item.isActive?'Activo':'Inactivo'}</small></div><div className="tm-actions"><button type="button" className="tm-edit" disabled={busy} onClick={()=>edit(item)}>Editar</button><button type="button" className={item.isActive?'off':''} disabled={busy} onClick={()=>toggle(item)}>{item.isActive?'Desactivar':'Activar'}</button></div></div>)}</div></div></div></section>}
  {!canManage&&<p className="tm-readonly">Tu perfil tiene acceso de consulta. La creación y activación de territorio requiere el rol Administrador o Técnico.</p>}
  {tree.map(center=><section className="m-farm" key={center.id}><header><div className="m-farm-icon">⌂</div><div><small>{center.code}</small><h2>{center.name}</h2><p>{center.location}</p></div></header>{center.farms.map(farm=><div className="m-farm-body" key={farm.id}><h3>💧 {farm.name}</h3>{farm.blocks.map(block=><article key={block.id}><div><small>{block.code} · {block.soilType??'Suelo sin clasificar'}</small><b>{block.name}</b><span>{fmt(block.areaHectares)} ha</span></div><div>{block.sectors.map(sector=><section className="tm-sector" key={sector.id}><header><small>{sector.code}</small><b>{sector.name}</b><span>{fmt(sector.areaHectares)} ha · pendiente {fmt(sector.slopePercent)}%</span></header><div className="m-zone-grid">{sector.zones.map(zone=><div className="m-zone-card" key={zone.id}><i className={zone.sensor?'on':''}/><strong>{zone.name}</strong><span>{zone.sensor??'Sin sensor principal'}</span><small>{zone.status} · {fmt(zone.areaHectares)} ha</small></div>)}</div></section>)}</div></article>)}</div>)}</section>)}
  <p className="m-tip">La jerarquía presenta la relación completa y el sensor principal asignado. Los registros inactivos permanecen en el panel de gestión para poder reactivarlos.</p>
 </>
}
